### ISSUE TITLE
Add Rain Animation in the Dark Forest Scene

### ISSUE THREAD

**Issue by jimenezz22** [ByteBuildersLabs/StarkHack2024FrontEndv2#110]
### Scope
We need to add a new rain animation to the entire Dark Forest scene. The animation must be constant and subtle rain in the scene DarkForest, pixel art and 2D style.
### How rain could be implemented?
- You will need to create a new empty object in the scene hierarchy to add everything related to the rain animation inside.
- If you need to add new assets to the rain, they must be added to the path: Assets/Animations/RainAnimations 
- Could you use Unity's Particle System to create this animation.
- We want the animation to be similar to what is shown in the first few minutes of the following video. Use it as a reference: https://www.youtube.com/watch?v=wrpuJkjaSiQ
- Don't touch the order and sorting layers
- Do not delete or change any assets that currently exist
- This is the hierarchy of DarkForest Scene:
<img width="266" alt="Screenshot 2024-10-29 at 5 09 49 PM" src="https://github.com/user-attachments/assets/e2db3bf9-35c0-45cc-bd16-f98320055829">

### How to apply?
- Please follow the contribution guidelines in the [readme](https://github.com/ByteBuildersLabs/ByteBeastsFrontend/blob/main/README.md) file

**Comment by CristopherAguilar10** [comment]
hi, i would like to work on this issue!

**Comment by jimenezz22** [comment]
assigned to you @CristopherAguilar10
