### ISSUE TITLE
fix rain bugs between scenes

### ISSUE THREAD

**Issue by jimenezz22** [ByteBuildersLabs/StarkHack2024FrontEndv2#118]
The game starts good, when it enters the Dark Forest the rain works good, but when I returns to the Forest the rain moves to this scene which should not happen. The same thing happens for the town scene.

**Comment by CristopherAguilar10** [comment]
I can fix the problem, in a few hours I have it🫡

**Comment by CristopherAguilar10** [comment]
I can fix the problem, in a few minutes i have it

**Comment by Benjtalkshow** [comment]
Can I be assigned to this?

**Comment by Michaelkingsdev** [comment]
May I pick this up? It will be my firs time contributing to this amazing project

**Comment by 0xdevcollins** [comment]
I'd like to take this issue.

**Comment by mimisavage** [comment]
Could I take on this issue?
