### ISSUE TITLE
Animate Fountain in Town Scene

### ISSUE THREAD

**Issue by jimenezz22** [ByteBuildersLabs/StarkHack2024FrontEndv2#120]
### Scope
We need to animate the water in the fountain in the town scene, we want a pixel art animation.

### How this fountain is implemented?
- The grid object contains all the objects in the scene
- The source is a prefab in the grid
- Don't touch the order and sorting layers.
- Don't remove or change the asset, just make them animated.
<img width="1111" alt="Screenshot 2024-11-02 at 11 03 16 AM" src="https://github.com/user-attachments/assets/f4b6af82-6a13-4536-90a4-73f6d722dbc7">

### How to apply?
Please follow the contribution guidelines in the [readme](https://github.com/ByteBuildersLabs/ByteBeastsFrontend/blob/main/README.md) file

**Comment by sebas11042** [comment]
Hello, can I work on this issue?
