### ISSUE TITLE
fix chimneys

### ISSUE THREAD

**Issue by jimenezz22** [ByteBuildersLabs/StarkHack2024FrontEndv2#124]

**Comment by Jemiiah** [comment]
@jimenezz22 can I help work on this issue

**Comment by jimenezz22** [comment]
> @jimenezz22 can I help work on this issue

@Jemiiah Please respect the issue tags, all issues with core-dev tag are for maintainers

**Comment by Jemiiah** [comment]
Hey @jimenezz22 my bad I didn’t read the tag properly
