### ISSUE TITLE
improve dark forest floor

### ISSUE THREAD

**Issue by jimenezz22** [ByteBuildersLabs/StarkHack2024FrontEndv2#126]
### Scope
We need to enhance the paths in the DarkForest scene. Currently, the paths are too geometric, and we want to add textured edges to make them more natural and visually appealing.

Please refer to the attached image of the forest scene to see how the paths currently look:
<img width="858" alt="Screenshot 2024-11-19 at 4 41 32 PM" src="https://github.com/user-attachments/assets/6a031b8b-885d-444f-9cea-9f952fececa8">

### How floor is currently implemented?
- In the grid object, there is an object named Ground 2, which represents the paths in the map
![image](https://github.com/user-attachments/assets/9d7c69cd-4126-42e9-829c-c32f6a412322)

- The Ground 2 object is actually a Tilemap. To interact with it, you need to open the Tile Palette panel, located at Window > 2D > Tile Palette
![image](https://github.com/user-attachments/assets/e56a90e1-1b20-45fd-8174-35a18a932f70)

- Once open, you should see something similar to this: (Attach a screenshot or provide further details as necessary)
![image](https://github.com/user-attachments/assets/81b22947-892e-4934-8dc4-de03f353d977)
 
- Make sure to select the tile palette named corners. This palette already contains the necessary assets to add the requested details and texture to the paths.
![image](https://github.com/user-attachments/assets/c33f3633-3bf5-4ce9-8e11-8591102a577b)

- Here’s a brief tutorial on how to enhance the paths using the Tile Palette:

https://github.com/user-attachments/assets/5bca8c3a-cbd3-44fd-a00f-0068294a38f4

### How to apply?
- Please follow the contribution guidelines in the [readme](https://github.com/ByteBuildersLabs/ByteBeastsFrontend/blob/main/README.md) file

**Comment by danielcdz** [comment]
Can I help with this one?

**Comment by jimenezz22** [comment]
yessir youk know

**Comment by martinvibes** [comment]
hey @jimenezz22 Can I attempt this issue?
i'm an experienced frontend developer and would love to work on this issue

**Comment by Yunusabdul38** [comment]
would like to help out with this issue
@jimenezz22 Can I attempt this issue?

**Comment by Yunusabdul38** [comment]
@jimenezz22 Can I attempt this issue?
would like to help out with this issue

**Comment by SudiptaPaul-31** [comment]
Can I please work on this issue?

**Comment by 0xdevcollins** [comment]
I’d love to work on this task.

**Comment by deeseeker** [comment]
Hello Admin, this is my first time finding this repo. I am a frontend developer and I have contributed in that capacity to Starknet React and Starknet Quest. I would like to work on this issue.

Thanks

**Comment by jimenezz22** [comment]
issues will be assigned when odhack 10 starts

**Comment by jimenezz22** [comment]
To assign issues we only take into account those applications via OnlyDust and really show how to resolve the issue. Single line comments will be ignored

**Comment by shokuyansh** [comment]
May I take care of this?

**Comment by Josue19-08** [comment]
Hi, I'm Josué, and I'm part of the Dojo Coding community. I have experience in programming languages such as Angular, React, C#, .NET, C++, PHP, Python, Java, Node.js, and JavaScript, among others. I'm passionate about software development and enjoy contributing to open-source projects, applying my knowledge to solve problems in a practical way. Additionally, I’m working on the project Citizen Of Arcanis, where I’ve had to use Unity, so I’m also skilled with this tool.

I would enhance the paths in the DarkForest scene by using the Tile Palette panel and selecting the corners palette. I would carefully add textured edges to the paths by placing the appropriate tiles from the palette, ensuring they blend seamlessly with the existing design. This will create a more natural and visually appealing look. Once the edits are complete, I would test the scene for consist
ency and submit the changes following the contribution guidelines in the README.

**Comment by Benjtalkshow** [comment]
I’d like to resolve this.

**Comment by ShantelPeters** [comment]
May I pick this up?

**Comment by Jemiiah** [comment]
Hello ser can i work on this issue

**Comment by Supa-mega** [comment]
May I try my hand at this?

**Comment by josephchimebuka** [comment]
Hello jimenezz22 I am Joseph I am a frontend developer and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchimebuka. I'll enhance the path and improve the dark forest floor by also following the detailed process laid out. I 'll complete it in 3-4 days

**Comment by aniruddhaaps** [comment]
The dark forest floor will be improved by replacing existing paths with a layered tile system. This would give more flexibility to the texture design and transition. Use Unity's tilemap system with custom rules to generate seamless edges and a diversity of terrain automatically. This will ensure that it is looking polished and easy to maintain.

**Comment by jimenezz22** [comment]
@aniruddhaaps assigned to you

**Comment by aniruddhaaps** [comment]
Thanks @jimenezz22 working right away
