### ISSUE TITLE
Reimplement Trees in the DarkForest Scene

### ISSUE THREAD

**Issue by jimenezz22** [ByteBuildersLabs/StarkHack2024FrontEndv2#127]
### Scope
Currently, there is a bug with the trees in the DarkForest scene as they were implemented as a single object, which caused issues and led to their removal. We now need to reimplement the trees.

Please refer to the attached image of the DarkForest scene to see how the trees previously looked, so you can reimplement them in similar locations.
![image](https://github.com/user-attachments/assets/c8170248-bcc6-4907-91fa-b5012fe24e5d)

### How to implement the issue?
![image](https://github.com/user-attachments/assets/c3602cd0-666b-42a0-8503-7fdae6e690b4)

- Each tree consists of two objects: the trunk and the foliage (leaves). We need to replicate this structure for each tree within the DarkForest scene.
- The process is simple: duplicate the existing tree structure and place it around the map according to the original layout shown in the reference image, so that the scene maintains a similar design to its previous state.

### How to apply?
- Please follow the contribution guidelines in the [readme](https://github.com/ByteBuildersLabs/ByteBeastsFrontend/blob/main/README.md) file

**Comment by CristopherAguilar10** [comment]
Well, put Marco to work 👏🏾

**Comment by Josue19-08** [comment]
It's time for @jimenezz22 to be @coxmars's boss

**Comment by jimenezz22** [comment]
hahahahhahaha

**Comment by Awointa** [comment]
Hello I am Awointa a javascript/React developer and I would be much grateful if given the opportunity  to make my first contribution using the OnlyDust platform

**Comment by GradleD** [comment]
Let me handle this issue!

**Comment by jimenezz22** [comment]
issues will be assigned when odhack 10 starts

**Comment by daksha-aeer** [comment]
Can I please be assigned this issue?

**Comment by jimenezz22** [comment]
To assign issues we only take into account those applications via OnlyDust and really show how to resolve the issue. Single line comments will be ignored

**Comment by shokuyansh** [comment]
I'd love to give this a go.

**Comment by aurlic** [comment]
Hey I would love to tackle this issue. I have not previously owrked with unity, but I think this could be a good starting point. I like to challenge myself and solve problems and think that this issue would be a good opportunity to start somewhere with unity. If I get assigned to this issue I will make sure to communicate and do my best. Thanks in advance !

**Comment by ShantelPeters** [comment]
I'd like to take this issue.

**Comment by Supa-mega** [comment]
May I take care of this?

**Comment by josephchimebuka** [comment]
Hello jimenezz22 I am Joseph I am a frontend developer and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchimebuka. The process for solving the issue has already been explained in the description I will reimplement the tree by duplicating the existing tree structure and place it around the map according to the original layout. I 'll complete it in 3-4 days max

**Comment by aniruddhaaps** [comment]
I will re-assign the trees for the DarkForest scene by duplicating the original tree structure, which is a two-object structure: trunk and foliage. Applying the reference image, I will strategically place the duplicated trees to replicate the same design as the original. I will also test whether the placement works out properly in Unity 2022.3.28.f1. Estimated time to complete: 2–3 days.

**Comment by jimenezz22** [comment]
@aurlic assigned to you
