### ISSUE TITLE
New BabyBeast Asset and Animations – Crystal Theme💎

### ISSUE THREAD

**Issue by juandiegocv27** [ByteBuildersLabs/StarkHack2024FrontEndv2#138]
### Scope  
We need to create a new BabyBeast asset with a **Crystal Theme🧊** for OD Hack 10. The design must maintain consistency with the current app's BabyBeast style, specifically the Baby Rabbit, while introducing unique crystalline elements. The goal is to enhance the app's variety and visual appeal with this themed asset.

### How BabyBeasts are currently designed?  
- BabyBeasts are designed as cute animals with a consistent style: rounded proportions, pastel tones, and clean, minimal details.  
- The Baby Rabbit model is the reference. It is stylized with simple shapes and subtle animations that make it feel alive in the app.

![babybeast copyresize](https://github.com/user-attachments/assets/8b8ab4ee-18d3-4689-ac62-89c2d6ed643a)

---

### Requirements  
1. **Design the Crystal BabyBeast💎:**  
   - Use the Baby Rabbit as a base for style and proportions.  
   - Add crystal-like features such as translucent or glowing body parts.  
   - Ensure the design feels cohesive with the current BabyBeasts.

2. **Create Animations:**  
   - Add animations that emphasize the crystalline elements:  
     - Subtle shimmering effects.  
     - Pulsating glows on crystal accents. 💠 

3. **Maintain Consistency:**  
   - Match the style of the current BabyBeasts, including similar proportions, color palettes, and aesthetic logic.  

---

### How to implement?  
1. Download and use any pixel art toolkit.
2. Create and Animate the new Beast.
3. Save it to Assets/BabySprites in this repo, please give us the asset with their respective Sprites.
4. Let us know with pr and talking directly to me https://t.me/juandixcode or in the community group: https://t.me/+aqxlW9ACIt5jODEx

---

### Cool Tools to Use  
- For creating and animating pixel art, we recommend using **[Aseprite](https://www.aseprite.org/)**. It’s a powerful tool for creating sprites, animations, and other pixel art elements or use another Toolkit of your choice.

### How to apply?  
Follow the contribution guidelines in the [README](https://github.com/ByteBuildersLabs/ByteBeastsFrontend/blob/main/README.md) file.  

Let me know by tagging me or @jimenezz22 😇🫶🏻

**Comment by Naomi-Gift** [comment]
Could I take a shot at this?
I will like to work on this design; can you please assign me when ODHack start?

**Comment by juandiegocv27** [comment]
> Could I take a shot at this? I will like to work on this design; can you please assign me when ODHack start?

issues will be assign when OD Hack start, via OnlyDust

**Comment by Josue19-08** [comment]
Hi, I'm Josué, and I'm part of the Dojo Coding community. I have experience in programming languages such as Angular, React, C#, .NET, C++, PHP, Python, Java, Node.js, and JavaScript, among others. I'm passionate about software development and enjoy contributing to open-source projects, applying my knowledge to solve problems in a practical way. Additionally, I’m working on the project Citizen Of Arcanis, where I’ve had to use Unity, so I’m also skilled with this tool.


I will use the Baby Rabbit as a base and edit it in LibreSprite, adding the necessary features to adapt it to the crystal theme. I will incorporate details such as translucent or glowing body parts and shimmering crystal accents to create a cohesive crystalline design. Additionally, I will add subtle animations, like shimmering effects and pulsating glows on the crystal features, ensuring the asset remains consistent with the original BabyBeasts style.

**Comment by ShantelPeters** [comment]
May I take this issue on?

**Comment by Jemiiah** [comment]
Hello I'm a frontend developer in web3 I have contributed in previous OD Hacks I have made over 70+ contribution in past OD Hacks I intend in solving this issue with the following approach :
1. Understand the Base Model (Baby Rabbit)
UI will use the Baby Rabbit as a base and edit it in LibreSprite, adding the necessary features to adapt it to the crystal theme.  Maintain rounded shapes and minimalist details.

2. Design Crystal Features
Create translucent crystal elements on the body with a subtle gradient (soft blues, purples, or greens).
Add a glowing effect for areas like the crystal accents and edges.

3. Create Animations
Shimmering Effect: Use CSS keyframes to simulate light reflecting off the crystals.
Pulsating Glows: Animate glowing accents using box-shadow or filter: glow for pulsating effects.

4. Ensure Cohesion with Existing Models
Make sure the crystal elements feel like a natural extension of the current BabyBeasts, maintaining consistency in proportions, style, and animation flow.

**Comment by Jemiiah** [comment]
Hello I'm a frontend developer in web3 I have contributed in previous OD Hacks I have made over 70+ contribution in past OD Hacks I intend in solving this issue with the following approach :

Understand the Base Model (Baby Rabbit): I would start by using the Baby Rabbit as a base, editing it in LibreSprite to introduce crystal features while maintaining its rounded, minimalist design.

Design Crystal Features: I’d create subtle, glowing crystal elements using soft gradients in colors like blues, purples, or greens.

Create Animations: I would implement shimmering effects through CSS keyframes and create pulsating glow animations using box-shadow or filter properties.

Ensure Cohesion: Finally, I would make sure the new design blends seamlessly with the existing BabyBeasts, preserving consistency in proportions, style, and animations.

**Comment by Amarjeet325** [comment]
I’d love to work on this task.

**Comment by Supa-mega** [comment]
Can I attempt this issue?

**Comment by josephchimebuka** [comment]
Hello @jimenezz22 Can I handle this issue I'll complete it in 2-3 days

**Comment by sandragcarrillo** [comment]
Would love to contribute to this issue, I'm a developer but also love illustration, so being able to create a character for ByteBeasts would be awesome. 

To solve this issue I will:

1. Create the character design using pixel art and matching the ByteBeasts style. 
2. Create the animations
3. Submit the PR including assets and sprites

**Comment by aniruddhaaps** [comment]
Hey @jimenezz22, I will use the Baby Rabbit as a basis, keeping its style and dimensions, to design the Dragon BabyBeast. The baby will consist of dragon-inspired parts, such as small wings, scales, horns, and a dragon-like tail, but it will maintain the overall look of the current BabyBeasts. Tail flicks, wing flutters, and minor fiery effects will be added as animation. I will make and animate the asset in Aseprite, save into the appropriate repository folder, and submit for PR review.

**Comment by juandiegocv27** [comment]
@sandragcarrillo you have the issue, any bug, blocker, new feature or idea, let me know via telegram please
