### ISSUE TITLE
New BabyBeast Asset and Animations – Dragon Theme🐉

### ISSUE THREAD

**Issue by juandiegocv27** [ByteBuildersLabs/StarkHack2024FrontEndv2#139]
### Scope  
We need to create a new BabyBeast asset with a **Dragon Theme🐲** for OD Hack 10. The design must maintain consistency with the current app's BabyBeast style, specifically the Baby Rabbit, while introducing unique dragon-inspired elements. The goal is to enhance the app's variety and visual appeal with this themed asset.

---

### How BabyBeasts are currently designed?  
- BabyBeasts are designed as cute animals with a consistent style: rounded proportions, pastel tones, and clean, minimal details.  
- The Baby Rabbit model is the reference. It is stylized with simple shapes and subtle animations that make it feel alive in the app.

![babybeast copyresize](https://github.com/user-attachments/assets/8b8ab4ee-18d3-4689-ac62-89c2d6ed643a)

---

### Requirements  
1. **Design the Dragon BabyBeast🐉:**  
   - Use the Baby Rabbit as a base for style and proportions.  
   - Add dragon-inspired features, such as:  
     - Small wings.  
     - Scales or horns.  
     - A dragon-like tail.  
   - Ensure the design feels cohesive with the current BabyBeasts.

2. **Create Animations:**  
   - Add animations that emphasize the dragon elements:  
     - Tail flicks.  
     - Small wing flutters.  
     - Fiery gestures or effects.  

3. **Maintain Consistency:**  
   - Match the style of the current BabyBeasts, including similar proportions, color palettes, and aesthetic logic.  

---

### How to implement?  
1. Download and use any pixel art toolkit.  
2. Create and animate the new Dragon BabyBeast.  
3. Save it to `Assets/BabySprites` in this repository and include the asset with its respective sprites.  
4. Let us know with a PR and by reaching out directly to me: [Telegram: @juandixcode](https://t.me/juandixcode) or in the community group: [Telegram Group](https://t.me/+aqxlW9ACIt5jODEx).

---

### Cool Tools to Use  
- For creating and animating pixel art, we recommend using **[Aseprite](https://www.aseprite.org/)**. It’s a powerful tool for creating sprites, animations, and other pixel art elements. Feel free to use any other toolkit of your choice.

---

### How to apply?  
Follow the contribution guidelines in the [README](https://github.com/ByteBuildersLabs/ByteBeastsFrontend/blob/main/README.md) file.  

Let me know by tagging me or **@jimenezz22** 😇🫶🏻

**Comment by Amarjeet325** [comment]
Hi ,  I am a proficient MERN stack developer with experience in full-stack development. I believe I can contribute effectively to this project. Could you kindly assign this issue/task to me? Thank you!

**Comment by aurlic** [comment]
Hello ! I would love trying to create a BabyBeast in this Dragon theme. This would be my first ever contribution on OnlyDust and I think I could really create something nice. I am a student at school 42, and one of the small project I had to do was a 2D game in C, where I had the occasion to design my own assets. I am sending this application along other for other theme BabyBeasts, and hope I will get the chance to work on one ! 
Thanks in advance

**Comment by ShantelPeters** [comment]
Can I be assigned to this?

**Comment by Jemiiah** [comment]
Hello ser please I would love to work on this issue I'm a frontend developer with over 70+ contributions on OD Hack I haven't contributed to this repository before but i would love the opportunity to work on this issue I plan on tackling this issue with the following approaches :

Developer Approach for the Dragon BabyBeast 🐉

1. Understand the Base Style
Analyze the Baby Rabbit model to extract its proportions, color palette, and animation logic.
Break down its SVG (or 3D) layers if applicable, focusing on reusable components.

2. Dragon Features Integration
Sketch or mockup small wings, scales/horns, and a dragon-like tail that maintain the rounded, minimalistic design.
Experiment with pastel, fiery tones (e.g., soft oranges, greens) to complement existing palettes.

3. Consistent Animations
Use subtle CSS or Lottie animations for:
Tail flicks: Keyframes simulating organic motion.
Wing flutters: Small amplitude oscillations.
Fiery gestures: Overlay particle effects (low opacity).

4.Test for Cohesion
Place the dragon alongside existing BabyBeasts to ensure uniformity.
Refine proportions, animations, and colors until visually cohesive.
Implementation

5. Use React/Three.js for animated BabyBeasts .
Create reusable components for wings, scales, and animations.

**Comment by Supa-mega** [comment]
May I take care of this?

**Comment by josephchimebuka** [comment]
Can I try solving this issue?

**Comment by josephchimebuka** [comment]
Hello @jimenezz22 Can I handle this issue I'll complete it in 2-3 days

**Comment by sandragcarrillo** [comment]
Would love to contribute to this issue, I'm a developer but also love illustration, so being able to create a character for ByteBeasts would be awesome. 

To solve this issue I will:

1. Create the character design using pixel art and matching the ByteBeasts style. 
2. Create the animations
3. Submit the PR including assets and sprites

**Comment by aniruddhaaps** [comment]
Hey @jimenezz22, I will design the Dragon BabyBeast by using the Baby Rabbit as a base, maintaining its style and proportions. The asset will feature dragon-inspired elements like small wings, scales, horns, and a dragon-like tail while preserving the current BabyBeasts' cohesive aesthetic. I will add animations such as tail flicks, wing flutters, and subtle fiery effects. Using Aseprite, I will create and animate the asset, save it to the specified repository folder, and submit a PR for review.

**Comment by Iwueseiter** [comment]
Could I try solving this?

**Comment by juandiegocv27** [comment]
@Iwueseiter you have the issue, any idea, new feature or blocker, let me know via Telegram, please let me know about your idea in this days plase, asap

**Comment by Iwueseiter** [comment]
> @Iwueseiter you have the issue, any idea, new feature or blocker, let me know via Telegram, please let me know about your idea in this days plase, asap

Alright sir

**Comment by juandiegocv27** [comment]
> > @Iwueseiter you have the issue, any idea, new feature or blocker, let me know via Telegram, please let me know about your idea in this days plase, asap
> 
> Alright sir

Hiii @Iwueseiter  let me know what´s your progress with your issue between this 24 hours please

**Comment by Iwueseiter** [comment]
Noted
