### ISSUE TITLE
New BabyBeast Asset and Animations – Dark Magic Theme🔮

### ISSUE THREAD

**Issue by juandiegocv27** [ByteBuildersLabs/StarkHack2024FrontEndv2#140]
### Scope  
We need to create a new BabyBeast asset with a **Dark Magic Theme🪄✨** for OD Hack 10. The design must maintain consistency with the current app's BabyBeast style, specifically the Baby Rabbit, while introducing unique dark magic-inspired elements. The goal is to enhance the app's variety and visual appeal with this themed asset.  

---

### How BabyBeasts are currently designed?  
- BabyBeasts are designed as cute animals with a consistent style: rounded proportions, pastel tones, and clean, minimal details.  
- The Baby Rabbit model is the reference. It is stylized with simple shapes and subtle animations that make it feel alive in the app.

![babybeast copyresize](https://github.com/user-attachments/assets/8b8ab4ee-18d3-4689-ac62-89c2d6ed643a)

---

### Requirements  
1. **Design the Dark Magic BabyBeast🖤🔮:**  
   - Use the Baby Rabbit as a base for style and proportions.  
   - Add dark magic-inspired features, such as:  
     - Purple hues. 🟣  
     - Smoky or shadowy parts. 🌫️  
     - Glowing dark features like eyes or magical accents.  

2. **Create Animations:**  
   - Add animations that emphasize the dark magic theme:  
     - Swirling effects resembling shadows or mist. 🌪️  
     - Glowing eyes. 👀✨  
     - Subtle, eerie shadow movements.  

3. **Maintain Consistency:**  
   - Match the style of the current BabyBeasts, including similar proportions, color palettes, and aesthetic logic.  

---

### How to implement?  
1. Download and use any pixel art toolkit.  
2. Create and animate the new Dark Magic BabyBeast.  
3. Save it to `Assets/BabySprites` in this repository and include the asset with its respective sprites.  
4. Let us know with a PR and by reaching out directly to me: [Telegram: @juandixcode](https://t.me/juandixcode) or in the community group: [Telegram Group](https://t.me/+aqxlW9ACIt5jODEx).  

### Cool Tools to Use  
- For creating and animating pixel art, we recommend using **[Aseprite](https://www.aseprite.org/)**. It’s a powerful tool for creating sprites, animations, and other pixel art elements. Feel free to use any other toolkit of your choice.  

### How to apply?  
Follow the contribution guidelines in the [README](https://github.com/ByteBuildersLabs/ByteBeastsFrontend/blob/main/README.md) file.  

Let me know by tagging me or **@jimenezz22** 🎯

**Comment by Amarjeet325** [comment]
Hi ,  I am a proficient MERN stack developer with experience in full-stack development. I believe I can contribute effectively to this project. Could you kindly assign this issue/task to me? Thank you!

**Comment by Josue19-08** [comment]
Hi, I'm Josué, and I'm part of the Dojo Coding community. I have experience in programming languages such as Angular, React, C#, .NET, C++, PHP, Python, Java, Node.js, and JavaScript, among others. I'm passionate about software development and enjoy contributing to open-source projects, applying my knowledge to solve problems in a practical way. Additionally, I’m working on the project Citizen Of Arcanis, where I’ve had to use Unity, so I’m also skilled with this tool.


I will use the Baby Rabbit as a base and edit it in LibreSprite, adding the necessary features to adapt it to the dark magic theme. I will incorporate details such as purple tones, shadow effects and glow in the eyes or magic elements. I will also add subtle animations, such as misty movements or shadows, to reinforce the sense of mystery, always keeping consistency with the original BabyBeasts style.

**Comment by aurlic** [comment]
Hello ! I would love trying to create a BabyBeast in this Dark Magic theme. This would be my first ever contribution on OnlyDust and I think I could really create something nice. I am a student at school 42, and one of the small project I had to do was a 2D game in C, where I had the occasion to design my own assets.

**Comment by ShantelPeters** [comment]
I’d like to resolve this.

**Comment by Supa-mega** [comment]
Let me handle this issue!

**Comment by josephchimebuka** [comment]
Hello @jimenezz22 Can I handle this issue I'll complete it in 2-3 days

**Comment by aniruddhaaps** [comment]
hey @jimenezz22, I'll make Dark Magic BabyBeast using Baby Rabbit as a foundation so that proportion and style stays consistent. The design will have dark magic properties, like purple tones, smoky effects, and glowing elements, with animations that include swirling shadows and glowing eyes. I'll draw and animate this asset in Aseprite and deliver it to the given folder within the repository for feedback.

**Comment by Iwueseiter** [comment]
I'd love to work on this!

**Comment by juandiegocv27** [comment]
@aniruddhaaps you have the issue, any idea, new feature or blocker, let me know via Telegram

**Comment by juandiegocv27** [comment]
@ShantelPeters you have the issue, any idea, new feature or blocker, let me know via Telegram

**Comment by juandiegocv27** [comment]
@ShantelPeters you have the issue, any idea, new feature or blocker, let me know via Telegram, asap

**Comment by aniruddhaaps** [comment]
Hey wait, why I was unassigned @juandiegocv27 :(

**Comment by juandiegocv27** [comment]
> Hey wait, why I was unassigned @juandiegocv27 :(

because you can only have one issue per repository, you already have one in the improve dark forest floor 🙏🏻🫡

**Comment by ShantelPeters** [comment]
> @ShantelPeters you have the issue, any idea, new feature or blocker, let me know via Telegram, asap

Okay sir .. Thank you
