### ISSUE TITLE
Reimplement Gravestones in the DarkForest Scene

### ISSUE THREAD

**Issue by jimenezz22** [ByteBuildersLabs/StarkHack2024FrontEndv2#141]
### Scope
We need to reimplement the gravestones in the DarkForest scene. They were previously removed due to a bug, but this issue has been resolved in recent commits. It is now time to reintroduce each gravestone.

Please use the attached image to see the original positions of the gravestones in the scene and place them accordingly.
![image](https://github.com/user-attachments/assets/c3e06da1-ab58-45c9-b051-277708fb7148)

### How to implement the issue?
- We already have an example gravestone available. Your task is to duplicate the Grave object, which includes the entire gravestone along with its components.
- Duplicate the Grave object as many times as necessary and position the duplicates around the map so that it resembles the previous design shown in the reference image.

### How to apply?
Please follow the contribution guidelines in the [readme](https://github.com/ByteBuildersLabs/ByteBeastsFrontend/blob/main/README.md) file

**Comment by NueloSE** [comment]
I'd love to work on this!

**Comment by Benjtalkshow** [comment]
Mind if I try this one?

**Comment by josephchimebuka** [comment]
Hello  I am Joseph I am a frontend developer and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchimebuka. I would like to handle this

**Comment by Amarjeet325** [comment]
Hi ,  I am a proficient MERN stack developer with experience in full-stack development. I believe I can contribute effectively to this project. Could you kindly assign this issue/task to me? Thank you!

**Comment by ShantelPeters** [comment]
Can I handle this task?

**Comment by Supa-mega** [comment]
Can I jump on this task?

**Comment by sebas11042** [comment]
I am an advanced computer science student with experience in Java, JavaScript, and Unity. I am currently part of SunsetLabs, where I am responsible for the frontend development of the game Citizen of Arcanis, which we are working on in Unity 3D. This role has provided me with practical experience in asset management, animations, and UI systems in Unity. Given my experience in Unity 3D, I am confident in my ability to tackle issues in Unity 2D and implement solutions efficiently.

I propose to address the reimplementation of the gravestones in the DarkForest scene, following the instructions provided in the scope of the issue and using the attached reference image to correctly position each gravestone in its original place.

**Comment by 0xDeon** [comment]
Could I try solving this?
I am a new contributor to Bytebeats and would love the opportunity to work on this

How I plan to solve this issue
I'll duplicate the gravestone gameobject and position them to precisely match the reference image

ETA: 24 Hrs

**Comment by aniruddhaaps** [comment]
Firstly reinstall the gravestones in the DarkForest scene by duplicating the existing grave prefab and placed exactly as shown in the reference image. Check its placement for alignment and spacing as if done correctly to turn out like the original layout. Testing should be done enough that there should be no issues associated with the reintroduction of gravestones back into the scene.

**Comment by jimenezz22** [comment]
@DanielEmmanuel1 assigned to you

**Comment by 0xDeon** [comment]
Thank u
Will get on it immediately
