### ISSUE TITLE
New BabyBeast Asset and Animations – Light Theme✨

### ISSUE THREAD

**Issue by juandiegocv27** [ByteBuildersLabs/StarkHack2024FrontEndv2#142]
### Scope  
We need to create a new BabyBeast asset with a **Light Theme🌟✨** for OD Hack 10. The design must maintain consistency with the current app's BabyBeast style, specifically the Baby Rabbit, while introducing unique celestial and light-inspired elements. The goal is to enhance the app's variety and visual appeal with this radiant-themed asset.

---

### How BabyBeasts are currently designed?  
- BabyBeasts are designed as cute animals with a consistent style: rounded proportions, pastel tones, and clean, minimal details.  
- The Baby Rabbit model is the reference. It is stylized with simple shapes and subtle animations that make it feel alive in the app.

![babybeast copyresize](https://github.com/user-attachments/assets/8b8ab4ee-18d3-4689-ac62-89c2d6ed643a)

---

### Requirements  
1. **Design the Light BabyBeast💡👼:**  
   - Use the Baby Rabbit as a base for style and proportions.  
   - Add light-themed features, such as:  
     - Glowing halos or radiant textures. ✨  
     - Golden accents for a celestial vibe. 🌙  
     - Subtle highlights to give a luminous feel.  

2. **Create Animations:**  
   - Add animations that highlight the ethereal and luminous nature:  
     - Pulsing light effects around the BabyBeast. 💫  
     - Graceful glowing movements, like a soft halo shimmer.  
     - Sparkling or radiant bursts to emphasize its light theme.  

3. **Maintain Consistency:**  
   - Match the style of the current BabyBeasts, including similar proportions, color palettes, and aesthetic logic.  

---

### How to implement?  
1. Download and use any pixel art toolkit.  
2. Create and animate the new Light BabyBeast.  
3. Save it to `Assets/BabySprites` in this repository and include the asset with its respective sprites.  
4. Let us know with a PR and by reaching out directly to me: [Telegram: @juandixcode](https://t.me/juandixcode) or in the community group: [Telegram Group](https://t.me/+aqxlW9ACIt5jODEx).  

---

### Cool Tools to Use  
- For creating and animating pixel art, we recommend using **[Aseprite](https://www.aseprite.org/)**. It’s a powerful tool for creating sprites, animations, and other pixel art elements. Feel free to use any other toolkit of your choice.  

### How to apply?  
Follow the contribution guidelines in the [README](https://github.com/ByteBuildersLabs/ByteBeastsFrontend/blob/main/README.md) file.  

Let me know by tagging me or **@jimenezz22** 🔥😎

**Comment by ryzen-xp** [comment]
Can I try solving this issue?

**Comment by Yunusabdul38** [comment]
I’d like to help with this.

**Comment by martinvibes** [comment]
Is it okay if I tackle this?

**Comment by mimisavage** [comment]
Could I be assigned to this?

**Comment by Naomi-Gift** [comment]
May I be assigned to this?

**Comment by Amarjeet325** [comment]
Hi ,  I am a proficient MERN stack developer with experience in full-stack development. I believe I can contribute effectively to this project. Could you kindly assign this issue/task to me?  Thank you

**Comment by Josue19-08** [comment]
Hi, I'm Josué, and I'm part of the Dojo Coding community. I have experience in programming languages such as Angular, React, C#, .NET, C++, PHP, Python, Java, Node.js, and JavaScript, among others. I'm passionate about software development and enjoy contributing to open-source projects, applying my knowledge to solve problems in a practical way. Additionally, I’m working on the project Citizen Of Arcanis, where I’ve had to use Unity, so I’m also skilled with this tool.

I will use the Baby Rabbit as a base and edit it in LibreSprite, adding the necessary features to adapt it to the light theme. I will incorporate details such as glowing halos, radiant textures, and golden accents for a celestial touch. I will also add subtle animations, such as pulsing light effects, soft sparkles, and ethereal movements to enhance the luminous feel, always maintaining consistency with the original BabyBeasts style.

**Comment by ShantelPeters** [comment]
Let me handle this issue!

**Comment by Michaelkingsdev** [comment]
Can I take this from here?

**Comment by Supa-mega** [comment]
May I pick this up?

**Comment by josephchimebuka** [comment]
Hello @jimenezz22 Can I handle this issue I'll complete it in 2-3 days

**Comment by aniruddhaaps** [comment]
For a new light theme BabyBeast asset to be created, the solution can be:

The shiny BabyBeast must have dreamy features with soft gradients, bright accents, and celestial highlights so that it fits the current style. This light theme should be driven home using lighting effects with smooth animations. It must keep the proportions along with the aesthetic logic of the existing style for smoother integration.

**Comment by juandiegocv27** [comment]
@Mystic-Nayy you have the issue, any idea, new feature or blocker, let me know via Telegram

**Comment by Naomi-Gift** [comment]
@juandiegocv27 Alright i will sir

**Comment by juandiegocv27** [comment]
> @juandiegocv27 Alright i will sir

Hiii @Mystic-Nayy let me know what´s your progress with your issue between this 24 hours please
