### ISSUE TITLE
Create Issue Creation Template

### ISSUE THREAD

**Issue by jimenezz22** [ByteBuildersLabs/StarkHack2024FrontEndv2#159]
### Scope 
- Create an issue creation template to facilitate the creation of issues in the repository. 
- Add the template in the .github folder of this repository. 

### How to implement the template?
The template must have at least these parts:
- Scope
- How to implement the issue?
- How to apply?
Please follow the contribution guidelines in the [readme](https://github.com/ByteBuildersLabs/ByteBeastsFrontend/blob/main/README.md) file
- Feel free to add new points to the template

### How to apply?
Please follow the contribution guidelines in the [readme](https://github.com/ByteBuildersLabs/ByteBeastsFrontend/blob/main/README.md) file

**Comment by mimisavage** [comment]
Would love to tackle this!

**Comment by zintarh** [comment]
Could I take on this issue?

**Comment by raizo07** [comment]
Let me try this one!

**Comment by SYLVIANNORUKA** [comment]
May I take this issue on?I am a Front-end and smart contract developer. I am proficient in tailwind css, Next Js, Typescript, JavaScript, . I would love to contribute to this project.

**Comment by abdegenius** [comment]
Can I handle this task?

**Comment by Steph3097** [comment]
Hey! im Sttef and I would love to assist on this! I have over five years of experience in front-end development.
Im part of Dojo Coding
For this task, I would Add the template to the .github folder adding the requested fields .
Thank you for your time and consideration!

**Comment by Naomi-Gift** [comment]
Could I be assigned to this?

**Comment by AdejareSamad** [comment]
May I handle this issue?

**Comment by Ibinola** [comment]
Can I start working on this?

I have worked on documentation on an open source project [here](https://github.com/trypear/pear-landing-page/pull/93).

**Comment by emarc99** [comment]
Can I tackle this one?

**Comment by kayceeDev** [comment]
Would love to tackle this!

**Comment by GideonBature** [comment]
Could I try solving this?

**Comment by ShantelPeters** [comment]
Could I take over this issue?

**Comment by EmmanuelAR** [comment]
Hello team Im Emmanuel Aguero from Costa Rica, Dojo coding member and Go Stark Me team member.
I will like to work on this issue, i will follow the instructions to create the new template

let me know!

**Comment by vestor-dev** [comment]
hey sir i would love to work on this issue 
i'm a blockchain dev and i would love to handle this issue 
assign me and i'll get to work

**Comment by Villarley** [comment]
Hi, I’m Santiago Villarreal Arley, a proactive and communicative developer with experience in Web3. I’m a proud member of Dojo Coding and have worked on several scalable solutions, including blockchain-based platforms. I’ve also won a Web3 hackathon Buildathon for my work on BuildMyEvent, showcasing my ability to deliver impactful solutions.

I’ve previously contributed to ByteBeasts Frontend, where I successfully implemented features and addressed issues. 

To tackle this issue:
I will ensure clear communication about the steps needed to resolve it and provide a detailed estimate and resolution plan. I’ll also reference my past contributions to validate my familiarity with the repository and Unity practices.

ETA: 12-48 hours. Feel free to reach out via Telegram

**Comment by TheSQLguy** [comment]
It's how I would go on to create the issue creation template:

Scope: First, create a markdown file named issue_template.md to standardize issue submissions from the.github folder present in the repository.
The template content should include how you implement the issue, followed by how to apply or, if needed, backgrounds or additional notes to improve the description and action ability behind issues.
Implementation: Add brief instructions for filling out each section of the template, following the contribution guidelines of the repository.
Commit and Push: Once the template is ready, commit it with a meaningful message like:
```
vbnet
feat: add issue creation template to.github folder
Push the changes to a new branch and submit a PR for review.

**Comment by Nityam573** [comment]
I’m interested in this one.

**Comment by Kom02** [comment]
Hi, I’m Kevin Obando, a full-stack software developer with 2 years of experience. Currently, I’m exploring the world of blockchain and am eager to gain hands-on experience in this field.

**Comment by olisaagbafor** [comment]
Can I take care of this issue?

**Comment by DuendexCR** [comment]
Is this issue still available?

**Comment by michojekunle** [comment]
Can I be assigned to this?

**Comment by pheobeayo** [comment]
Can I be assigned to this?
