### ISSUE TITLE
New BabyBeast Asset and Animations – Light Theme✨ (Butterfly)

### ISSUE THREAD

**Issue by jimenezz22** [ByteBuildersLabs/StarkHack2024FrontEndv2#161]
## Scope
We need to create a new BabyBeast asset with a **Light Theme✨** for a Butterfly. The design must maintain consistency with the current BabyBeast implemented, while introducing unique glowing and light-based features.

---

## What is a BabyBeast?
BabyBeasts are designed as cute magical animals with a consistent style: rounded proportions, soft tones, and minimal yet expressive details.  
You can use this one as an example of a Light Theme Assets/BabySprites/babybeast light.gif

---

### Design the Light BabyBeast✨:
- Use the Baby **Assets/BabySprites/babybeast light.gif** as a base for style and proportions.  
- Add glowing and radiant features, such as translucent wings or soft golden accents.  
- Ensure the design feels cohesive with the current BabyBeasts.

### Create Animations:
1. **Idle Animation (breathing)**:  
   - Subtle wing flutters or light pulsations.
2. **Additional Animations**:  
   - Eating animation: Gentle pecking or sipping motion with some fruit
   - Sleeping animation: Wings close slightly with soft dimming light.  
   - Happiness animation: Energetic flutters with glowing sparkles.  
   - Bathing animation: Shimmering body with radiant ripples.  

### Maintain Consistency:
- Match the proportions, color palettes, and aesthetic logic of the current BabyBeasts.  
- All animations should feel smooth and aligned with the game’s magical theme.

---

## How to Implement?
1. Use any pixel art or sprite animation toolkit of your choice.
2. Create and animate the **Light BabyBeast** (Butterfly).
3. Save all assets to the `Assets/BabySprites` folder in this repository, ensuring proper naming conventions for the files.

---

## Cool Tools to Use
- **Aseprite**: A powerful tool for creating and animating sprites and pixel art.  
- **Piskel**: A free online tool for sprite creation and animation.  
- Feel free to use any toolkit that works best for you.

---

## How to Apply?
1. Follow the contribution guidelines provided in the README file.  
2. Submit your pull request with the asset and animations in their respective folders.  
3. Ensure all animations are properly tested before submission.

---

We’re excited to see your contribution!🦋✨

**Comment by Supa-mega** [comment]
Can I tackle this one?

**Comment by mimisavage** [comment]
May I take this issue on?

**Comment by zintarh** [comment]
May I pick this up?

**Comment by abdegenius** [comment]
Can I take care of this issue?

**Comment by josephchimebuka** [comment]
Is it okay if I take this?

**Comment by Naomi-Gift** [comment]
I’d like to work on this.

**Comment by Tonyverse-ops** [comment]
I'd be happy to do this. I am good at drawing and animating using Aseprite.

**Comment by AdejareSamad** [comment]
May I handle this issue?

**Comment by lauchaves** [comment]
Hey im lau chaves from dojo coding costa rica, haven't had the opportunity to contribute to this project but it really catches my attention! I would like to give a hand on this one

I have over 5 years of experience with JavaScript, ReactJS,React Native TypeScript, and Ruby. I’m now enthusiastic about web3 and eager to learn more! I’m also a member of Dojo Coding Costa Rica. 

Id follow the steps mentioned to do the baby beast butterfly :3, id look inspo on the other beast already implemented

**Comment by sandragcarrillo** [comment]
I’d love to work on this task, I contributed to create a Crystal BabyBeast including its animations and it was a great experience. 

Would love to continue contributing to ByteBeast in this ODHack.  This is how I would work on it:

1. Create the butterfly design based on the requirements in this issue
2. Create animations
3. Create sprites 

I would also share the progress adding a commit to my PR in every completed step.

**Comment by Amizeey** [comment]
Can I jump on this task?

**Comment by obacollins-lab** [comment]
Can I start working on this?
I'd deliver to the best of your expectations, worked on project similar in past.

**Comment by ShantelPeters** [comment]
I’d like to resolve this.

**Comment by KVMillz** [comment]
Can I still work on as well? I have experience with designing and animating nft's

**Comment by Amarjeet325** [comment]
Can I take this from here?

**Comment by suhas-sensei** [comment]
Could I take on this issue?

**Comment by suhas-sensei** [comment]
i have the required experience in unity and making animations for gaming proects prev. 
i will add the idle as well as additional animations as requested and implement it as posted. 🦋

**Comment by vestor-dev** [comment]
hey sir i would love to work on this issue 
i'm a blockchain dev and i would love to handle this issue 
assign me and i'll get to work

**Comment by TheSQLguy** [comment]
To address this issue, I would design a Light BabyBeast Butterfly based on the light theme base. This includes glowing translucent wings and soft golden accents to be used to enhance its bright aesthetic. Smooth animations created would include idle (gently fluttering wings and pulsing light), eating (sipping from a fruit), sleeping (wings closing and dimming lights), happiness (energetic fluttering and sparkles), and bathing (shimmering ripples of light). Assets will be saved within Assets/BabySprites, given the correct naming conventions to ensure it aligns with the magical style of the BabyBeast.

**Comment by DuendexCR** [comment]
Let me handle this issue!

**Comment by NueloSE** [comment]
Mind if I try this one?

**Comment by lauchaves** [comment]
🤩 awesome will open a PR soon!

**Comment by lauchaves** [comment]
@jimenezz22 all set! 🚀
