### ISSUE TITLE
New BabyBeast Asset and Animations – Darkness Theme🌑 (Wolf Pup)

### ISSUE THREAD

**Issue by jimenezz22** [ByteBuildersLabs/StarkHack2024FrontEndv2#162]
## Scope
We need to create a new BabyBeast asset with a **Darkness Theme🌑** for a Wolf Pup. The design must maintain consistency, while introducing unique dark and shadowy features. 
---

## What is a BabyBeast?
BabyBeasts are designed as cute magical animals with a consistent style: rounded proportions, soft tones, and minimal yet expressive details.  
You can use this one as an example of a Dark Theme Assets/BabySprites/babybeast-dark-magic-theme-base.gif

---

### Design the Darkness BabyBeast🌑:
- Use the Baby **Assets/BabySprites/babybeast-dark-magic-theme-base.gif** as a base for style and proportions.  
- Add shadowy and dark features, such as:  
  - Deep purple or black tones with subtle gradients. 🟣⚫  
  - Smoky or mist-like accents around the body. 🌫️  
  - Glowing eyes with a mysterious hue. 👀✨  

### Create Animations:
1. **Idle Animation (breathing)**:  
   - Subtle shadowy pulsations or mist swirling around the wolf pup.  
2. **Additional Animations**:  
   - Eating animation: Playful chewing of a bone but calculated with bright eyes.
   - Sleeping animation: Curling into a ball as shadows envelop it.  
   - Happiness animation: Energetic tail wagging with a shadowy ripple effect.  
   - Bathing animation: Mist-like ripples flowing across its fur.  

### Maintain Consistency:
- Match the proportions, color palettes, and aesthetic logic of the current BabyBeasts.  
- All animations should feel smooth and aligned with the game’s magical and shadowy theme.

---

## How to Implement?
1. Use any pixel art or sprite animation toolkit of your choice.
2. Create and animate the **Darkness BabyBeast** (Wolf Pup).
3. Save all assets to the `Assets/BabySprites` folder in this repository, ensuring proper naming conventions for the files.

---

## Cool Tools to Use
- **Aseprite**: A powerful tool for creating and animating sprites and pixel art.  
- **Piskel**: A free online tool for sprite creation and animation.  
- Feel free to use any toolkit that works best for you.

---

## How to Apply?
1. Follow the contribution guidelines provided in the README file.  
2. Submit your pull request with the asset and animations in their respective folders.  
3. Ensure all animations are properly tested before submission.

---

We’re excited to see your contribution! 🐺🌑

**Comment by mimisavage** [comment]
Can I start working on this?

**Comment by abdegenius** [comment]
Can I jump on this task?

**Comment by Tonyverse-ops** [comment]
Hey ,can i be assigned to this , i have a good background with Aseprite tools and creating animations with Aseprite as well.

**Comment by Supa-mega** [comment]
Can I tackle this one?

**Comment by AdejareSamad** [comment]
Would love to tackle this!

**Comment by Naomi-Gift** [comment]
Could I be assigned to this?
I have worked on a similar issue in the last Odhack , I can perfectly work on this without any issue

**Comment by Steph3097** [comment]
Hi! Im Sttef!
I'm part of Dojo Coding! I’m excited about the opportunity to design and animate a BabyBeast! I have over five years of experience in front end, but i also like to create and design fun stuff like creating magical animals 
Here’s my approach to bringing this shimmering creature to life:
- I’ll use Assets/BabySprites/babybeast-dark-magic-theme-base.gif as a base to maintain style and proportions.
- Animations for Personality like eating, sleeping, breathing...
- I’ll ensure the proportions, colors, and animation logic align perfectly with the existing BabyBeasts 
I can’t wait to bring this magical creature to life! thank you for consider my application!

**Comment by sandragcarrillo** [comment]
I’d love to work on this task, I contributed to create a Crystal BabyBeast including its animations and it was a great experience. 

Would love to continue contributing to ByteBeast in this ODHack.  This is how I would work on it:

1. Create the wolf pup design based on the requirements in this issue
2. Create animations
3. Create sprites 

I would also share the progress adding a commit to my PR in every completed step.

**Comment by Amizeey** [comment]
I'd love to give this a go.

**Comment by obacollins-lab** [comment]
Let me try this one! 
I've worked on projects like this before, can I be assigned this?

**Comment by ShantelPeters** [comment]
Can I jump on this task?

**Comment by Amarjeet325** [comment]
Can I tackle this one?

**Comment by suhas-sensei** [comment]
i have the required experience in makingg animations and workign with unity. I will implement and work on the animation for thw wolf pup 🐺 as requested and test out the chagnes.

**Comment by TheSQLguy** [comment]
In order to handle this task, I would Design a darkness BabyBeast Wolf Pup with deep purple/black tones, smoky accents, and glowing mysterious eyes, referring to the dark magic theme base. Create smooth animations such as idle (swirling shadowy mist), eating (chewing a bone with glowing eyes), sleeping (curling into shadows), happiness (tail wagging with shadow ripples), and bathing (mist ripples across fur). Save all assets in Assets/BabySprites using proper naming conventions to align with the magical BabyBeast style.

**Comment by Nityam573** [comment]
Let me try this one!

**Comment by NueloSE** [comment]
Could I grab this task?
