### ISSUE TITLE
New BabyBeast Asset and Animations – Darkness Theme🌑 (Owl)

### ISSUE THREAD

**Issue by jimenezz22** [ByteBuildersLabs/StarkHack2024FrontEndv2#163]
## Scope
We need to create a new BabyBeast asset with a **Darkness Theme🌑** for a Baby Owl. The design must maintain consistency, while introducing unique dark and starry features.

---

## What is a BabyBeast?
BabyBeasts are designed as cute magical animals with a consistent style: rounded proportions, soft tones, and minimal yet expressive details.  
You can use this one as an example of a Dark Theme: `Assets/BabySprites/babybeast-dark-magic-theme-base.gif`

---

### Design the Darkness BabyBeast🌑:
- Use the `Assets/BabySprites/babybeast-dark-magic-theme-base.gif` as a base for style and proportions.  
- Add starry and dark features, such as:  
  - Deep navy blue or black tones with subtle gradients. ⚫💫  
  - Starry accents on the wings or body. ✨🌌  
  - Glowing, galaxy-like eyes. 👀🌟  

### Create Animations:
1. **Idle Animation (breathing)**:  
   - Gentle swaying or wing adjustments, with subtle star twinkles.  
2. **Additional Animations**:  
   - Eating animation: Pecking at food with precise, deliberate movements while glowing eyes flicker.  
   - Sleeping animation: Nestling down as wings fold and stars softly dim.  
   - Happiness animation: Energetic flapping with stars sparkling around.  
   - Bathing animation: Star-like ripples flowing across its feathers.  

### Maintain Consistency:
- Match the proportions, color palettes, and aesthetic logic of the current BabyBeasts.  
- All animations should feel smooth and aligned with the game’s magical and shadowy theme.

---

## How to Implement?
1. Use any pixel art or sprite animation toolkit of your choice.  
2. Create and animate the **Darkness BabyBeast** (Owl).  
3. Save all assets to the `Assets/BabySprites` folder in this repository, ensuring proper naming conventions for the files.

---

## Cool Tools to Use
- **Aseprite**: A powerful tool for creating and animating sprites and pixel art.  
- **Piskel**: A free online tool for sprite creation and animation.  
- Feel free to use any toolkit that works best for you.

---

## How to Apply?
1. Follow the contribution guidelines provided in the README file.  
2. Submit your pull request with the asset and animations in their respective folders.  
3. Ensure all animations are properly tested before submission.

---

We’re excited to see your contribution! 🦉🌑

**Comment by mimisavage** [comment]
May I take care of this?

**Comment by abdegenius** [comment]
Can I work on this, please?

**Comment by josephchimebuka** [comment]
Can I work on this, please?

**Comment by Kingsuite** [comment]
May I handle this issue?

**Comment by Tonyverse-ops** [comment]
Hey,i would love to work on this. I am good at pixelated art and i have very good drawing and animating skills using aesprite.

**Comment by Supa-mega** [comment]
Can I take this issue?

**Comment by AdejareSamad** [comment]
Mind if I take this issue?

**Comment by aurlic** [comment]
Hey  I would really love to be able to do this issue, I've had the chance to contribute once for the dark forest trees and really loved working on this project. If I was given this issue I would create a Beast that would match the overall aesthetics. Thanks in advance !

**Comment by sandragcarrillo** [comment]
I’d love to work on this task, I contributed to create a Crystal BabyBeast including its animations and it was a great experience. 

Would love to continue contributing to ByteBeast in this ODHack.  This is how I would work on it:

1. Create the owl design based on the requirements in this issue
2. Create animations
3. Create sprites 

I would also share the progress adding a commit to my PR in every completed step.

**Comment by Amizeey** [comment]
Can I be assigned to this?

**Comment by obacollins-lab** [comment]
I'm a seasoned 3d artist, Can I be assigned this issue?

**Comment by ShantelPeters** [comment]
Can I jump on this task?

**Comment by KVMillz** [comment]
Can I please work on this? I have experience with designing and animating nft's

**Comment by respp** [comment]
Hello! I am part of the Dojo community and am excited about the opportunity to make my first contributions to OnlyDust.
I would love to resolve this issue as I have experience with animations and want to contribute to ByteBeast, which has always been a dream of mine as I've wanted to work on a video game. ByteBeast would be a great opportunity. My focus would be entirely on creating a beautiful design and bringing it to life with a smooth animation.

**Comment by suhas-sensei** [comment]
i have the required experiene in unity and making animations as such for certain projects done previously. I'll create the Darkness BabyBeast Owl using Aseprite to maintain the cute style while incorporating starry effects and galaxy-like features in the eyes and wings wchich will include the breathing animation with gentle star twinkles, followed by the eating, sleeping, happiness 🦉🌌

**Comment by Amarjeet325** [comment]
Can I take this from here?

**Comment by vestor-dev** [comment]
hey sir i would love to work on this issue 
i'm a blockchain dev and i would love to handle this issue 
assign me and i'll get to work

**Comment by TheSQLguy** [comment]
In order to address this issue, I would design a Darkness BabyBeast Owl using the provided dark magic theme base as a reference, with deep navy or black tones, starry accents, and glowing galaxy-like eyes. Create animations such as idle (star twinkles with gentle wing movements), eating (precise pecking with flickering eyes), sleeping (dimmed stars with folded wings), happiness (energetic flapping with sparkling stars), and bathing (star-like ripples). Ensure consistency with the BabyBeast style and save assets in Assets/BabySprites with proper naming conventions.

**Comment by Nityam573** [comment]
Is it okay if I tackle this?

**Comment by Baronvil** [comment]
I would love to take on this issue.

**Comment by DuendexCR** [comment]
Can I work on this, please?

**Comment by NueloSE** [comment]
Let me try this one!

**Comment by jimenezz22** [comment]
@respp hey sir any updates here?

**Comment by respp** [comment]
> @respp hey sir any updates here?
Hi @jimenezz22 , apologies for the delay in replying, I hadn't seen this earlier. There will be updates coming soon. Thank you for your patience
