### ISSUE TITLE
New BabyBeast Asset and Animations – Fire Theme🔥 (Horse)

### ISSUE THREAD

**Issue by jimenezz22** [ByteBuildersLabs/StarkHack2024FrontEndv2#164]
## Scope
We need to create a new BabyBeast asset with a **Fire Theme🔥** for a Baby Horse. The design must maintain consistency, while introducing unique fiery and energetic features.

---

## What is a BabyBeast?
BabyBeasts are designed as cute magical animals with a consistent style: rounded proportions, soft tones, and minimal yet expressive details.  
You can use this one as an example of a Fire Theme: `Assets/BabySprites/babybeast new dragon.gif`

---

### Design the Fire BabyBeast🔥:
- Use the `Assets/BabySprites/babybeast new dragon.gif` as a base for style and proportions.  
- Add fiery features, such as:  
  - Vibrant orange and red tones with glowing gradients. 🔥🟠  
  - Flaming mane and tail. 🐴⚡  
  - Brighter, ember-like hooves. ✨💥  

### Create Animations:
1. **Idle Animation (breathing)**:  
   - Gentle movement of the flaming mane and tail, with subtle glowing hooves.  
2. **Additional Animations**:  
   - Eating animation: Lifting its head with embers flickering around the mouth.  
   - Sleeping animation: Laying down as flames reduce to a soft flicker.  
   - Happiness animation: Energetic galloping in place with flames intensifying briefly.  
   - Bathing animation: Flames interacting with a mist-like water effect.  

### Maintain Consistency:
- Match the proportions, color palettes, and aesthetic logic of the current BabyBeasts.  
- All animations should feel smooth and aligned with the game’s magical and fiery theme.

---

## How to Implement?
1. Use any pixel art or sprite animation toolkit of your choice.  
2. Create and animate the **Fire BabyBeast** (Horse).  
3. Save all assets to the `Assets/BabySprites` folder in this repository, ensuring proper naming conventions for the files.

---

## Cool Tools to Use
- **Aseprite**: A powerful tool for creating and animating sprites and pixel art.  
- **Piskel**: A free online tool for sprite creation and animation.  
- Feel free to use any toolkit that works best for you.

---

## How to Apply?
1. Follow the contribution guidelines provided in the README file.  
2. Submit your pull request with the asset and animations in their respective folders.  
3. Ensure all animations are properly tested before submission.

---

We’re excited to see your contribution! 🐴🔥

**Comment by mimisavage** [comment]
Can I try solving this issue?

**Comment by abdegenius** [comment]
I'd love to give this a go.

**Comment by josephchimebuka** [comment]
Can I work on this, please?

**Comment by Naomi-Gift** [comment]
Can I try solving this issue?

**Comment by Supa-mega** [comment]
Can I attempt this issue?

**Comment by Steph3097** [comment]
Hi! Im Sttef!
I’m thrilled about the opportunity to design and animate the enchanting Crystal BabyBeast! I have over five years of experience in front end, but i also like to create and design fun stuff like creating magical animals 
Here’s my approach to bringing this shimmering creature to life:
- I’ll useAssets/BabySprites/babybeast new dragon.gif as a base to maintain style and proportions.
- I'll add Animations for Personality like eating, sleeping, breathing...
- I’ll ensure the proportions, colors, and animation logic align perfectly with the existing BabyBeasts 
I can’t wait to bring this magical creature to life! 
Thank you for consider my application!

**Comment by AdejareSamad** [comment]
Can I try solving this issue?

**Comment by sandragcarrillo** [comment]
I’d love to work on this task, I contributed to create a Crystal BabyBeast including its animations and it was a great experience. 

Would love to continue contributing to ByteBeast in this ODHack.  This is how I would work on it:

1. Create the horse design based on the requirements in this issue
2. Create animations
3. Create sprites 

I would also share the progress adding a commit to my PR in every completed step.

**Comment by Amizeey** [comment]
I'd love to work on this!

**Comment by obacollins-lab** [comment]
Could I try solving this? I'm a 3d artist and I've worked on such projects before.

**Comment by Tonyverse-ops** [comment]
can i work on this please? I know how to use Aseprite to sketch and animate.

**Comment by ShantelPeters** [comment]
Could I be assigned to this?

**Comment by KVMillz** [comment]
@jimenezz22  Can I work on this? I have experience with designing and animating

**Comment by suhas-sensei** [comment]
I'd like to handle this task.

**Comment by Amarjeet325** [comment]
Can I tackle this one?

**Comment by TheSQLguy** [comment]
To address this issue, I would design a Fire BabyBeast Horse using the dragon asset provided as a starting point, adding a fiery mane, tail, ember-like hooves, and vibrant orange/red tones. Create animations including idle (mane and tail flickering), eating (embers flickering), sleeping (flames reducing), happiness (galloping with intensified flames), and bathing (flames interacting with mist). Ensure consistency with the BabyBeasts style and save all assets in the Assets/BabySprites folder with proper naming conventions.

**Comment by Baronvil** [comment]
I would love to take on this issue.

**Comment by emarc99** [comment]
I'd love to give this a go.

**Comment by DuendexCR** [comment]
Is it okay if I take this?

**Comment by Iwueseiter** [comment]
Can I contribute to this one?
I have a solid background with animation libraries and I implemented the dragon babybeast used here as reference, I will be glad to contribute to this project.

**Comment by NueloSE** [comment]
Could I take on this issue?

**Comment by jimenezz22** [comment]
@Steph3097 hi steph any updates here?

**Comment by Steph3097** [comment]
> @Steph3097 hi steph any updates here?

@jimenezz22 Hello! I already create the PR, let me know if you have more changes or questions!
