### ISSUE TITLE
New BabyBeast Asset and Animations – Crystal Theme💎 (Eagle)

### ISSUE THREAD

**Issue by jimenezz22** [ByteBuildersLabs/StarkHack2024FrontEndv2#165]
## Scope
We need to create a new BabyBeast asset with a **Crystal Theme💎** for a Baby Eagle. The design must maintain consistency, while introducing unique translucent and light-refracting features.

---

## What is a BabyBeast?
BabyBeasts are designed as cute magical animals with a consistent style: rounded proportions, soft tones, and minimal yet expressive details.  
You can use this one as an example of a Crystal Theme: `Assets/BabySprites/crystalbabybeast.gif`

---

### Design the Crystal BabyBeast💎:
- Use the `Assets/BabySprites/crystalbabybeast.gif` as a base for style and proportions.  
- Add crystal-like features, such as:  
  - Translucent feathers that refract light into rainbow colors. 🌈🦅  
  - A glowing body with subtle shimmering effects. ✨💫  
  - Elegant and sharp details on the wings and beak.  

### Create Animations:
1. **Idle Animation (breathing)**:  
   - Gentle wing movements with light refracting through the feathers.  
2. **Additional Animations**:  
   - Eating animation: Precise pecking at food while light shimmers on its feathers.  
   - Sleeping animation: Wings folding gracefully with light dimming softly.  
   - Happiness animation: Energetic flapping with rainbow-like sparkles.  
   - Bathing animation: Light ripples shimmering across its translucent feathers.  

### Maintain Consistency:
- Match the proportions, color palettes, and aesthetic logic of the current BabyBeasts.  
- All animations should feel smooth and aligned with the game’s magical and crystalline theme.

---

## How to Implement?
1. Use any pixel art or sprite animation toolkit of your choice.  
2. Create and animate the **Crystal BabyBeast** (Eagle).  
3. Save all assets to the `Assets/BabySprites` folder in this repository, ensuring proper naming conventions for the files.

---

## Cool Tools to Use
- **Aseprite**: A powerful tool for creating and animating sprites and pixel art.  
- **Piskel**: A free online tool for sprite creation and animation.  
- Feel free to use any toolkit that works best for you.

---

## How to Apply?
1. Follow the contribution guidelines provided in the README file.  
2. Submit your pull request with the asset and animations in their respective folders.  
3. Ensure all animations are properly tested before submission.

---

We’re excited to see your contribution! 🦅💎

**Comment by mimisavage** [comment]
I’d like to work on this.

**Comment by zintarh** [comment]
May I be assigned to this?

**Comment by abdegenius** [comment]
Could I take on this issue?

**Comment by Naomi-Gift** [comment]
Could I take on this issue?
I have worked on a similar task in the last ODHack, I will be glad to take this one too

**Comment by Supa-mega** [comment]
Could I grab this task?

**Comment by Steph3097** [comment]
Hi! Im Sttef!
I’m thrilled about the opportunity to design and animate the enchanting Crystal BabyBeast! I have over five years of experience in front end, but i also like to create and design fun stuff like creating magical animals 
Here’s my approach to bringing this shimmering creature to life:
- I’ll use Assets/BabySprites/crystalbabybeast.gif as a base to maintain style and proportions.I’ll add translucent feathers that refract light into rainbow colors, a glowing body with shimmering effects, and elegant, sharp details on the wings and beak to embody its crystalline essence.
- I'll add Animations for Personality like eating, sleeping, breathing...
- I’ll ensure the proportions, colors, and animation logic align perfectly with the existing BabyBeasts while emphasizing the crystalline theme for a cohesive yet standout addition.
This project excites me as it merges technical expertise with creativity, and I can’t wait to bring this magical creature to life! 
Thank you for consider my application!

**Comment by AdejareSamad** [comment]
I’d like to work on this.

**Comment by aurlic** [comment]
I would really like to work on this issue and try my hand at designing an awesome Byte Beast!

**Comment by Luluameh** [comment]
I'd like to take this issue.

**Comment by Amizeey** [comment]
May I take this issue on?

**Comment by obacollins-lab** [comment]
I've worked on such projects before, Can I be assigned this issue.

**Comment by Tonyverse-ops** [comment]
I'd like to handle this task. i have a good understanding of animating and sketching to proportions using Aseprite.

**Comment by ShantelPeters** [comment]
Can I tackle this one?

**Comment by KVMillz** [comment]
@jimenezz22 can I work on this? I'm a designer

**Comment by DuendexCR** [comment]
May I pick this up?

**Comment by suhas-sensei** [comment]
i have the required experience in unity andd making animations as such. I'll create the Crystal BabyBeast Eagle using Aseprite to maintain the established cute style while adding translucent crystal effects and rainbow refractions, aslo including the breathing animation prioritizing smooth wing movements, followed by the eating, sleeping, happiness, and bathing animations

**Comment by Amarjeet325** [comment]
Can I tackle this one?

**Comment by vestor-dev** [comment]
hey sir i would love to work on this issue 
i'm a blockchain dev and i would love to handle this issue 
assign me and i'll get to work

**Comment by TheSQLguy** [comment]
To address this issue, I would design a Crystal BabyBeast Eagle using the style provided as a base, with translucent, light-refracting feathers, a glowing body, and elegant crystalline details. Create smooth animations, including idle (breathing), eating, sleeping, happiness, and bathing, with shimmering and rainbow effects aligned with the magical theme. Save all assets in the Assets/BabySprites folder with proper naming conventions to ensure consistency.

**Comment by michojekunle** [comment]
I’m interested in this one.

**Comment by pheobeayo** [comment]
May I take this issue on?

**Comment by NueloSE** [comment]
May I try my hand at this?

**Comment by suhas-sensei** [comment]
thanks for the assignment.

**Comment by juandiegocv27** [comment]
hi @suhas-sensei is there any update in this issue? let me know please between 24 hours

**Comment by suhas-sensei** [comment]
yeah, im sending a pr today @juandiegocv27
