### ISSUE TITLE
Animate the trees

### ISSUE THREAD

**Issue by jimenezz22** [ByteBuildersLabs/StarkHack2024FrontEndv2#92]
### Scope:
We need to animate all the trees in each unity scene (Forest, Dark Forest and Town). The goal is to make animations for the leaves of the trees as if the wind were hitting them. 
### How trees are currently implemented? 
We have two types of trees with different colors, we need to animate both types:
<img width="818" alt="Screenshot 2024-10-20 at 8 16 52 PM" src="https://github.com/user-attachments/assets/bd350544-ba33-473d-a92e-06b4a2785781">

- All trees is located inside the "trees" object inside the "Grid" object for each scene. 
- Each tree inside the map is an object composed of two objects called "trunk" that refers to the trunk and "foliage" that refers to the leaves.
- Object "BorderTrees" refers to the trees on the map border.
- In the inspector panel you can see the characteristics and components of each tree.
- Don't touch the order and sorting layers
- Don't remove or change the asset of any tree, just make them animated
 
<img width="269" alt="Screenshot 2024-10-20 at 8 24 54 PM" src="https://github.com/user-attachments/assets/bc339f67-167a-4deb-8cea-ddfac664b5a4">

### How to apply?
- Please follow the contribution guidelines in the [readme](https://github.com/ByteBuildersLabs/ByteBeastsFrontend/blob/main/README.md) file

**Comment by Jemiiah** [comment]
@jimenezz22 I have read all the guidelines to contribute to this project when OD Hacks I would love to work on this issue

**Comment by jimenezz22** [comment]
> @jimenezz22 I have read all the guidelines to contribute to this project when OD Hacks I would love to work on this issue

Hi @Jemiiah, thank you for your interests to contribute to ByteBeats, we will start assigning issues when the ODHack 9 starts on October 24 and issues will be assigned through OnlyDust

**Comment by Jemiiah** [comment]
alrifht sureee

**Comment by sebas11042** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bytebeasts).

### My background and how it can be leveraged
I am an advanced computer science student with experience in Java, JavaScript, and Unity. I am currently part of SunsetLabs, where I am responsible for the frontend development of the game Citizen of Arcanis, which we are working on in Unity 3D. This role has provided me with practical experience in asset management, animations, and UI systems in Unity. Given my experience in Unity 3D, I am confident in my ability to tackle issues in Unity 2D and implement solutions efficiently, such as character animations and UI enhancements.

### How I plan on tackling this issue
I can create an animation system for the leaves of each tree using tweens to generate movements that imitate the effect of wind, causing the leaves to move in random directions and with varying intensities. Additionally, I can set up an Animator to control the leaf animations for both types of trees, creating animation cycles that play continuously and adjusting the speed based on wind direction for a more realistic effect. I look forward to working on this issue!

**Comment by CristopherAguilar10** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bytebeasts).

### My background and how it can be leveraged
I have development experience in Unity, where I have worked on various tasks such as setting up character animations, configuring camera systems and implementing interactive elements in scenes. My previous experience with similar tasks on the Sunset Labs project has prepared me well to address this issue effectively and deliver high quality results.

### How I plan on tackling this issue

I would like to contribute to this issue. I am currently working on the Sunset Labs project with Unity and have already completed several tasks, such as setting up animations and configuring the character camera. I have experience with Unity, including working with animations and visual effects, and I’m ready to take on the challenge of animating the trees. I plan to create animations that simulate the natural movement of the branches and leaves in the wind while maintaining the pixel art style to ensure it blends seamlessly with the environment. This will help bring the scene to life and enhance the overall atmosphere of the game.

**Comment by martinvibes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bytebeasts).

### My background and how it can be leveraged
hello @ i'm an experienced frontend developer and a blockchain developer i would love to work on this issue 
Pleasee kindly assign :)

**Comment by 0xdevcollins** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bytebeasts).

### My background and how it can be leveraged
Hi, I'm Collins a frontend and blockchain developer, and an active contributor on OnlyDust. You can check out my profile here: https://app.onlydust.com/u/0xdevcollins. This is my first time contributing to this repository, and I’m excited about the opportunity to contribute. Looking forward to collaborating!

### How I plan on tackling this issue
I’ll animate the trees in each Unity scene by creating leaf animations to simulate wind movement. I’ll focus on both tree types found under the "trees" object in the "Grid." The animations will be applied to the "foliage" objects while keeping everything else intact, including the "BorderTrees." I’ll make sure to follow the contribution guidelines in the readme for my updates.

**Comment by suhas-sensei** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bytebeasts).

### My background and how it can be leveraged
i have experience in game dev previously as personal projects and hoping to make use of them here and mark my first contribution in odhack

### How I plan on tackling this issue
I'll have the animation of trees by instancing a field of wind formed using perlin noise animating natural, propagating waves of motion across groups of trees so that tightly packed trees move in a fashion similar to that of more sparsely distributed trees. The foliage animation I will generate combines subtle pulsing of scale with sway rotation; intensity depends on position in the wind field, and done in a lightweight TreeAnimator component respectful of any existing hierarchy or sorting layers.

**Comment by od-hunter** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bytebeasts).

### My background and how it can be leveraged
Hi, please can I be assigned this please? This would be my first time contributing to this project and I would love to be the given the opportunity to contribute. I have experience in html, css, JavaScript,TypeScript and solidity, and Cairo.

### How I plan on tackling this issue
To solve this issue, I’ll take the following steps:
1. I’ll locate the "trees" GameObject inside the "Grid" for each scene. I’ll also identify the "trunk" and "foliage" GameObjects for each tree.

2. After that, I’ll use the Animation window to create a new animation clip (like `TreeFoliage_Sway`) for the "foliage" object. I’ll then add keyframes for ‘Position’ or ‘Rotation’ to simulate wind, creating a looping sway effect.

3. Then I’ll create an animator controller and assign the animation clip. I’ll make sure to attach the animator component to each tree's foliage in the inspector. I’ll reuse the same animation for all foliage objects across scenes, including "BorderTrees”. I can also add ‘Wind Zone’ for enhanced wind effects, if you want.

5. Lastly, I’ll test to ensure smooth animations and adjust as needed.

Please assign me, I’m ready to start work immediately.

**Comment by Benjtalkshow** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bytebeasts).

### My background and how it can be leveraged
I am a Full Stack Developer specializing in Next.js, TypeScript, Node.js, Cairo and Rust . With over 31 contributions across projects in the OnlyDust ecosystem, I’ve developed strong proficiency in delivering high-quality solutions and resolving complex issues within tight deadlines. My experience spans frontend, backend, smart contracts, and the optimization and maintenance of scalable codebases.

### How I plan on tackling this issue
To animate the trees in the Unity scenes (Forest, Dark Forest, and Town), we will create wind effects for the leaves of two tree types without altering their structure. 

I'll analyze the tree organization under the “trees” object within the “Grid” and develop a wind animation script targeting the foliage. Using Unity’s animation tools, I’ll simulate leaf movement with variations to mimic natural wind. This will also apply to the “BorderTrees” object.

Throughout, I'll maintain existing order and sorting layers, ensure seamless integration through testing, and document our process. This approach will enhance scene dynamics while preserving structure.

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bytebeasts).

### My background and how it can be leveraged
I have a solid background in game development and animation, particularly in Unity. My experience includes implementing animations, optimizing game performance, and understanding the principles of 3D modeling and scene management. This expertise enables me to effectively animate tree foliage while maintaining the integrity of the existing scene structure and assets.



### How I plan on tackling this issue
Identify Tree Structures: Locate the "trees" object within each scene's "Grid" object, ensuring I understand the hierarchy of "trunk" and "foliage" objects.

Animation Creation: Use Unity’s animation tools to create subtle leaf movements that mimic wind effects. This can be achieved by:

Applying simple oscillation to the foliage's rotation or scale.
Utilizing Unity’s Animation or Animator components to manage these animations.
Testing and Iteration: Playtest the animations in each scene (Forest, Dark Forest, and Town) to ensure they appear natural and enhance the visual experience without distracting from the gameplay.

Documentation and Guidelines: Follow the project’s contribution guidelines to maintain consistency and ensure the animations integrate seamlessly with existing assets.

**Comment by jimenezz22** [comment]
gm @sebas11042 assigned to you. Here a resource that can help you to resolve this issue, as you can see in the video, this project has some animated trees that could be a good reference

https://youtu.be/8Z9F24bG9CQ?si=BRFfiDIzKWdIWM05&t=13

feel free to research an use another reference, no problem

**Comment by sebas11042** [comment]
gm @jimenezz22 thanks for the assignment, now let's get to work!
