### ISSUE TITLE
Animate the flowers

### ISSUE THREAD

**Issue by jimenezz22** [ByteBuildersLabs/StarkHack2024FrontEndv2#93]
### Scope
We need to animate all the flowers in the unity scenes Forest and Town. The goal is to make animations for the flowers as if the wind were hitting them.
### How flowers are currently implemented?
We have two types of flowers with different colors, we need to animate both types:
<img width="854" alt="Screenshot 2024-10-20 at 8 37 03 PM" src="https://github.com/user-attachments/assets/aec10c9a-0e9f-4a5e-a48a-31f3eccc94e5">

- All flowers is located inside the "Flowers" object inside the "Grid" object for each scene.
- Each flower inside the map is an object called "FlowerType1" or "FlowerType2".
- In the inspector panel you can see the characteristics and components of each flower.
- Don't touch the order and sorting layers.
- Don't remove or change the asset of any flower, just make them animated.
<img width="267" alt="Screenshot 2024-10-20 at 8 43 10 PM" src="https://github.com/user-attachments/assets/0dd7afc7-bc18-4c20-b75e-2042294ef6e2">

### How to apply?
- Please follow the contribution guidelines in the [readme](https://github.com/ByteBuildersLabs/ByteBeastsFrontend/blob/main/README.md) file

**Comment by martinvibes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bytebeasts).

### My background and how it can be leveraged
hello @jimenezz22  i'm an experienced frontend developer and a blockchain developer i would love to work on this issue 
Pleasee kindly assign :)

### How I plan on tackling this issue
i would make sure it is working

**Comment by sebas11042** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bytebeasts).

### My background and how it can be leveraged
I am an advanced computer science student with experience in Java, JavaScript, and Unity. I am currently part of SunsetLabs, where I am responsible for the frontend development of the game Citizen of Arcanis, which we are working on in Unity 3D. This role has provided me with practical experience in asset management, animations, and UI systems in Unity. Given my experience in Unity 3D, I am confident in my ability to tackle issues in Unity 2D and implement solutions efficiently, such as character animations and UI enhancements.

### How I plan on tackling this issue
I believe I can set up an Animator for each type of flower, using different animation cycles to create natural movements that reflect the tilting and swaying of the flowers. I can also adjust the speed and frequency parameters of the animations to ensure they align with the environment, making the movement look more realistic. I will conduct tests in both scenes to verify that the animations integrate well and display correctly within the game's context. I am ready to get started on this issue if you allow me!

**Comment by CristopherAguilar10** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bytebeasts).

### My background and how it can be leveraged
I have development experience in Unity, where I have worked on various tasks such as setting up character animations, configuring camera systems and implementing interactive elements in scenes. My previous experience with similar tasks on the Sunset Labs project has prepared me well to address this issue effectively and deliver high quality results.

### How I plan on tackling this issue

I would like to contribute to this issue. I am currently working on the Sunset Labs project with Unity and have already completed several tasks, such as setting up animations and configuring the character camera. I have some experience with the tool, and I’m ready to take on the challenge of animating the flowers. I plan to implement subtle animations to simulate the natural movement of the flowers in the wind, with appropriate settings to ensure the effect integrates seamlessly with the environment.

**Comment by diegoTech14** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bytebeasts).

### My background and how it can be leveraged
Hello @jimenezz22

I'm a software engineer from Costa Rica and a proud member of Dojo Coding. I've contributed to projects like Go Stark Me, Coffiblocks, and DipDup, and I have experience with technologies such as C#, Cairo. I've created some basic animations using Unity so I think that can do this.

### How I plan on tackling this issue
For this issue I will:

`1.` Implement Animation: Using the flower spritesheets, I will animate the flowers based on the direction of the wind, ensuring that the animation corresponds naturally to direction of the wind.

`2.` Testing and Validation: I will thoroughly test the animation to confirm that all flowers are responding correctly to the wind direction, adjusting the animation if necessary to ensure accuracy.

Looking forward to your feedback!

Best regards,


Diego Duarte Fernández.

**Comment by suhas-sensei** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bytebeasts).

### My background and how it can be leveraged
i have experience in game dev previously as personal projects and hoping to make use of them here 

### How I plan on tackling this issue
I'll apply sine wave modulation on this visual "ripple" effect of flower patches with a harmonized flower animation system. Flowers would behave in response to a virtual wind vector changing direction at a slow pace. There should be a small difference in the frequency response between FlowerType1 and FlowerType2 so there is even more natural variety. Each flower will use custom lightweight scripts sampling its position for the phase offset; that creates meadow-like wave patterns, preserving existing sorting layers and hierarchies.

**Comment by Benjtalkshow** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bytebeasts).

### My background and how it can be leveraged
I am a Full Stack Developer specializing in Next.js, TypeScript, Node.js, Cairo and Rust . With over 31 contributions across projects in the OnlyDust ecosystem, I’ve developed strong proficiency in delivering high-quality solutions and resolving complex issues within tight deadlines. My experience spans frontend, backend, smart contracts, and the optimization and maintenance of scalable codebases.

### How I plan on tackling this issue
To animate the flowers in the Unity scenes (Forest and Town), I aim to create wind-like movements for two types of flowers without altering their existing structure or assets.

The implementation will begin by analyzing the current organization of the flowers, which are grouped under the “Flowers” object within the “Grid.” I will develop a wind animation script targeting each flower type, specifically focusing on the movement of their petals and stems.

Using Unity’s animation tools, I’ll create effects that simulate gentle swaying in response to wind, incorporating variations to enhance realism. I will ensure that the existing order and sorting layers remain unchanged and that no assets are modified.

Throughout the process, thorough testing will be conducted to guarantee seamless integration with the scenes, and I will document our methods for future reference.

**Comment by jancris100** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bytebeasts).

### My background and how it can be leveraged
I'm from dojo coding
All flowers are located inside the "Flowers" object within the "Grid" object of each scene. This means I'll access and manipulate the flowers under these objects, without changing their hierarchy, sorting layers, or assets.

### How I plan on tackling this issue
I'll create a simple swaying effect to simulate wind hitting the flowers. This can be done by rotating or scaling the flower models back and forth to create the illusion of them bending under the force of the wind.I'm proficient in C# scripting, which will allow me to customize the animations programmatically if needed for better performance or control.

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bytebeasts).

### My background and how it can be leveraged
I have a strong background in Unity game development, with a focus on animations and environmental enhancements. My experience includes creating lifelike animations for various assets, optimizing performance for mobile and PC, and adhering to project guidelines to ensure consistency across game elements. This expertise will allow me to effectively animate the flowers while ensuring they blend seamlessly into the existing scenes.

### How I plan on tackling this issue
To animate the flowers in the Unity scenes (Forest and Town), I will first identify the structure by navigating to the "Flowers" object within the "Grid," focusing on "FlowerType1" and "FlowerType2." Next, I will create animations using Unity’s Animation tool, applying gentle swaying motions through keyframes for slight rotations and scale variations to simulate wind effects. I will set the animation properties to ensure they loop smoothly and adjust playback settings for a natural motion. After that, I will playtest the animations in both scenes, tweaking speed and intensity for optimal visual impact. Throughout this process, I will adhere to the contribution guidelines, maintaining asset integrity and sorting layers.

**Comment by LazarusAA** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bytebeasts).

### My background and how it can be leveraged
Hi, I'm Alvaro Lazarus a new member of Dojo Coding, I've followed ByteBeast for a while and this seems like a really fun issue for me to contribute to the project. I have worked with Unity and other game engines before which makes me confident I can complete this issue with really nice result.

### How I plan on tackling this issue
- I will locate all flowers in the "Forest" and "Town" scenes under the "Flowers" and "Grid" objects.
- Animate both "FlowerType1" and "FlowerType2" to simulate wind using Unity's animation tools (Trying to match the wind from the Trees issue ).
- Maintain existing characteristics, sorting layers, and flower assets.
- And test animations to ensure they work smoothly without affecting other elements.

ETA: 48 hrs

**Comment by jimenezz22** [comment]
gm @CristopherAguilar10 assigned to you, feel free to research an implement the solution

**Comment by CristopherAguilar10** [comment]
> gm @CristopherAguilar10 assigned to you, feel free to research an implement the solution

gm @jimenezz22, thank you very much for the opportunity
