### ISSUE TITLE
Animate house chimneys

### ISSUE THREAD

**Issue by jimenezz22** [ByteBuildersLabs/StarkHack2024FrontEndv2#94]
### Scope
We need to animate all the house chimneys in the unity scene Town. The goal is to make animations for the house chimneys if someone were cooking inside.
### How house chimneys are currently implemented?
- All houses are an object inside the "Grid" object for the scene Town
- Each house object has inside it every object that makes up each part of the house, so one of this objects is the chimneys. 
- In the inspector panel you can see the characteristics and components of each house and chimneys.
- Don't touch the order and sorting layers.
- Don't remove or change the asset of any house and chimneys, just make them animated.

<img width="1125" alt="Screenshot 2024-10-21 at 3 05 34 PM" src="https://github.com/user-attachments/assets/f1e07b2a-55e4-452b-8b4b-7ce46240dfb9">

### How to apply?
- Please follow the contribution guidelines in the [readme](https://github.com/ByteBuildersLabs/ByteBeastsFrontend/blob/main/README.md) file

**Comment by Josue19-08** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bytebeasts).

### My background and how it can be leveraged
My name is Josué. I'm part of the Dojo Coding community and have worked on several projects, including some in Unity. I have experience with C#, .NET, Java, JavaScript, Angular, and Node.js. I love contributing to open-source projects, whether it's fixing bugs, adding new features, or improving documentation.

### How I plan on tackling this issue
I will identify the chimneys inside each house within the "Grid" object hierarchy. Then, I'll create a smoke animation (possibly using particles) and add it to the chimneys via an Animator. I'll ensure the animation loops continuously without modifying the sorting layers or any assets of the houses or chimneys

**Comment by sebas11042** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bytebeasts).

### My background and how it can be leveraged
I am an advanced computer science student with experience in Java, JavaScript, and Unity. I am currently part of SunsetLabs, where I am responsible for the frontend development of the game Citizen of Arcanis, which we are working on in Unity 3D. This role has provided me with practical experience in asset management, animations, and UI systems in Unity. Given my experience in Unity 3D, I am confident in my ability to tackle issues in Unity 2D and implement solutions efficiently, such as character animations and UI enhancements.

### How I plan on tackling this issue
I can animate the chimneys in the Town scene using Unity's particle system to create more realistic smoke effects that rise from the chimneys, simulating the cooking effect. I will also set up an Animator to control the smoke animation and ensure that it emits continuously, appearing only when there is activity in the chimneys. I'm excited to work on this issue!

**Comment by CristopherAguilar10** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bytebeasts).

### My background and how it can be leveraged
I have development experience in Unity, where I have worked on various tasks such as setting up character animations, configuring camera systems and implementing interactive elements in scenes. My previous experience with similar tasks on the Sunset Labs project has prepared me well to address this issue effectively and deliver high quality results.

### How I plan on tackling this issue

I would like to contribute to this issue. I am currently working on the Sunset Labs project with Unity and have already completed several tasks, such as setting up the animations, the character camera and implementing a minimap. I have some experience with the tool, and I am ready to take on the challenge of animating the chimneys. I plan to implement a particle system to simulate the smoke coming out of the chimneys, with the appropriate settings so that the effect blends seamlessly into the environment.
Thank you for considering my contribution.

**Comment by CollinsC1O** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bytebeasts).

### My background and how it can be leveraged
Hello I'm a front-end and blockchain developer. I will love to work on this issue. Please assign

**Comment by suhas-sensei** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bytebeasts).

### My background and how it can be leveraged
i have experience in game dev previously as personal projects and hoping to make use of them here and mark my first odhack contribution

**Comment by jancris100** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bytebeasts).

### My background and how it can be leveraged
With experience in Unity and particle effects, I have worked on environmental animations and special effects in various game projects. I'm a c# developer with 2 year of experience 

### How I plan on tackling this issue
Add a Particle System for Smoke:

For each chimney, I will add a Particle System that simulates smoke rising from the chimney.

Adjustments to the Particle System will include:

Shape: Cone-like shape for the smoke to rise upward.

Particle Lifespan: Particles will live for a short duration, giving the impression of smoke dissipating as it rises.

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bytebeasts).

### My background and how it can be leveraged
I have experience in Unity animation and asset management, specifically in animating environmental elements within scenes. This expertise allows me to create engaging and immersive experiences by bringing static objects to life through movement and interaction.

### How I plan on tackling this issue
I will animate the chimneys by applying a subtle smoke particle effect that simulates cooking. The animation will involve using the built-in animation tools in Unity to create a looping effect that can be triggered under specific conditions, ensuring that the chimneys appear lively and interactive without altering any existing assets or layers. This approach maintains the visual integrity of the scene while enhancing the overall ambiance.

**Comment by caxtonacollins** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bytebeasts).

### My background and how it can be leveraged
i am appling via https://app.onlydust.com/hackathons/odhack-90

I am Collins Caxton. I have worked on several projects, including some in Unity. I have experience with C#, .NET, Java, JavaScript, Angular, React, and Node.js. I love contributing to open-source projects, whether it's fixing bugs, adding new features, or improving documentation.

### How I plan on tackling this issue
firstly, i will try to understand the scene setup, open the Unity project and go to the 'town' scene and locate the grid object in the scene hierarchy which contains the house objects: i will check for chimneys in each house.

i will then create a new animation clip for the smoke configure the animation curves to make the effect look natural, with smooth transitions, add a Particle System to the chimney objects for the smoke effect also, i will implement animator controller to manage the animation state.

Lastly, Play the scene and test the animations to ensure that the smoke looks natural. I will love to contribute to this project. Thanks

**Comment by jimenezz22** [comment]
gm @Josue19-08 assigned to you. Here a resource that can help you to resolve this issue, as you can see in the video, this project has some animated chimneys that could be a good reference

https://learn.unity.com/project/creator-kit-rpg
https://youtu.be/l-sRhhjIvIw?si=VcLnZrh3Y0VjVfvl

feel free to research an use another reference, no problem

**Comment by Josue19-08** [comment]
gm @jimenezz22 Thank you, Sir! I´m working.
