### ISSUE TITLE
Animate Beasts in the Town Scene

### ISSUE THREAD

**Issue by jimenezz22** [ByteBuildersLabs/StarkHack2024FrontEndv2#95]
### Scope
- We need to animate all the beasts in the unity scene Town. The goal is to animate the beasts as if they are breathing.
- For the land beasts, we want a subtle breathing animation. For the flying beasts, we want a subtle wing flapping animation.
- The animations and assets for each animation should be placed in Assets/Animations/NewFolder.
- Please use this video as a reference to better understand the type of animation we are looking for:
https://www.youtube.com/shorts/fDZqo8WWiJw
### How beasts are currently implemented?
- The beasts are inside the main object called "beasts".
- Within this object are the beasts that make up the scene.
- In the inspector panel you can see the characteristics and components of each one.
- Don't touch the order and sorting layers.
- Don't remove or change the asset of any beast, just make them animated.

<img width="1512" alt="Screenshot 2024-10-21 at 3 33 50 PM" src="https://github.com/user-attachments/assets/09a74f28-5240-4e1f-89bc-70bf00be9e3a">

### How to apply?
- Please follow the contribution guidelines in the [readme](https://github.com/ByteBuildersLabs/ByteBeastsFrontend/blob/main/README.md) file

**Comment by sebas11042** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bytebeasts).

### My background and how it can be leveraged
I am an advanced computer science student with experience in Java, JavaScript, and Unity. I am currently part of SunsetLabs, where I am responsible for the frontend development of the game Citizen of Arcanis, which we are working on in Unity 3D. This role has provided me with practical experience in asset management, animations, and UI systems in Unity. Given my experience in Unity 3D, I am confident in my ability to tackle issues in Unity 2D and implement solutions efficiently, such as character animations and UI enhancements.

### How I plan on tackling this issue
My idea is to animate the beasts in the Town scene to enhance their movement. I plan to create or source the necessary animation assets for each beast, allowing them to move in four directions: forward, backward, left, and right. I will also set up an Animator Controller to manage the transitions between different animations based on movement inputs, using direction and speed parameters. I would love to work on this issue!

**Comment by CollinsC1O** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bytebeasts).

### My background and how it can be leveraged
Hello I'm a frontend and blockchain developer and I will love to take on this issue and get it solved. Please assign

**Comment by 0xdevcollins** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bytebeasts).

### My background and how it can be leveraged
Hi, I'm Collins a frontend and blockchain developer, and an active contributor on OnlyDust. You can check out my profile here: https://app.onlydust.com/u/0xdevcollins. This is my first time contributing to this repository, and I’m excited about the opportunity to contribute. Looking forward to collaborating!

### How I plan on tackling this issue
I'll animate the beasts in the Town scene by creating movement animations for each direction: forward, backward, right, and left. I'll locate the beasts within the "beasts" object and set up the animations using the appropriate assets in Unity's Animation section. Each beast will have its Animator configured without altering the existing order, sorting layers, or assets. I'll ensure to adhere to the contribution guidelines in the readme for my changes.

**Comment by martinvibes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bytebeasts).

### My background and how it can be leveraged
hello @ i'm an experienced frontend developer and a blockchain developer  i would love to work on this issue 
Pleasee kindly assign :)

### How I plan on tackling this issue
i would make sure it is pixel perfect

**Comment by suhas-sensei** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bytebeasts).

### My background and how it can be leveraged
i have experience in game dev previously as personal projects and hoping to make use of them here and mark my first odhack contribution

### How I plan on tackling this issue
beasts go roarrr

**Comment by od-hunter** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bytebeasts).

### My background and how it can be leveraged
Hi, please can I be assigned this please? This would be my first time contributing to this project and I would love to be the given the opportunity to contribute. I have experience in html, css, JavaScript,TypeScript and solidity, and Cairo.


### How I plan on tackling this issue
To solve this issue, I’d take the following steps:
1.⁠ ⁠First of all, I’ll prepare animation assets. I’ll gather sprites for forward, backward, right, and left movements for each beast.
2.⁠ ⁠⁠I’ll create animation clips. I’ll select the "beasts" gameobject in the hierarchy. I’ll also open the animation window and create separate animation clips (for, Beast1_Walk_Forward, Beast1_Walk_Backward, etc.) for each direction by dragging the respective sprites into the timeline and adjusting frame timings.
3.⁠ ⁠⁠Next, I’ll set up animator controller, that is, I’ll create an animator controller and assign it to each beast's animator component. I’ll then open the animator window and add the created animation clips as states.
4.⁠ ⁠⁠I’ll set up transitions between states in the animator window based on movement conditions (e.g., IsMoving, Direction).
5.⁠ ⁠⁠I’ll then implement movement logic in script. Next, I’ll create a BeastMovement C# script to handle input and control animations to 
fetch input for movement direction and trigger appropriate animations based on movement.
6.⁠ ⁠Lastly, I’ll test animations.

Please assign me, I’m ready to deliver a good work with clean codes.

**Comment by jancris100** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bytebeasts).

### My background and how it can be leveraged
I'm from dojo coding
Each beast already has specific characteristics and components, so I will only focus on adding movement animations without altering their current setup or assets.

### How I plan on tackling this issue
Each movement direction will require an appropriate image or sprite (front, back, left, and right), which will be used in the animation frames. I will verify the availability of these assets or request them if they don’t exist.With experience in Unity, 2D/3D animation, and C# scripting, I have successfully implemented character animations in various projects.

**Comment by Akshola00** [comment]
Would love to tackle this!

**Comment by mimisavage** [comment]
Hi, I'm Mimi sav, a frontend and blockchain developer, and I’m new to the OnlyDust platform. This is my first time contributing to this repository, and I’m excited about the opportunity to collaborate and bring my skills to the table. Looking forward to making a positive impact and working with the team!


To tackle animating the beasts in Unity, I would begin by examining how each beast is structured within the "beasts" object in the inspector panel. Without altering any sorting layers or existing assets, my focus would be on creating the appropriate movement animations for each beast. For every beast, I need to prepare four movement animations: forward, backward, right, and left. Using Unity's "Animation" section, I would create these movement loops, ensuring they correspond to their respective directional animations. Finally, I would set up an Animator for each beast, integrating it into the scene while preserving the current setup.

**Comment by aniruddhaaps** [comment]
I'm a javascript dev. A new-comer here, willing to and ready to contribute to solve the issue.

**Comment by ShantelPeters** [comment]
Can I take care of this issue?         I will review the current implementation of the beasts within the "beasts" object in the Unity scene. For land beasts, I will create a subtle breathing animation by adjusting the scale and position of the body parts to simulate inhaling and exhaling. For flying beasts, I will implement a gentle wing flapping animation using keyframe animation techniques. I will ensure that the animations are added to the specified folder (Assets,Animations,NewFolder) and keep the existing asset configurations intact. After animating, I will test the animations in the scene to ensure they perform as expected and meet the reference video standards.

**Comment by DotworldX** [comment]
Can I be assigned to this?

**Comment by deeseeker** [comment]
May I take care of this?

**Comment by Josue19-08** [comment]
My name is Josué. I'm part of the Dojo Coding community and have worked on several projects, including some in Unity. I have experience with C#, .NET, Java, JavaScript, Angular, and Node.js. I love contributing to open-source projects, whether it's fixing bugs, adding new features, or improving documentation.


I can take on this issue. I have experience working in Unity, especially with animations in my project Citizen of Arcanis. I’m confident I can make the necessary adjustments and ensure implementation.

**Comment by jimenezz22** [comment]
@Josue19-08 assigned to you

**Comment by Josue19-08** [comment]
@jimenezz22 Working! 🔨

**Comment by Jemiiah** [comment]
@Josue19-08 @jimenezz22 can I help work on this issue ?

**Comment by Josue19-08** [comment]
@jimenezz22 Sir, I´m ready to create PR.

**Comment by mimisavage** [comment]
I want to take on this issue, can I be assigned?
