### ISSUE TITLE
Change Assets of Gameplay Panels

### ISSUE THREAD

**Issue by jimenezz22** [ByteBuildersLabs/StarkHack2024FrontEndv2#97]
### Scope
- We need to change the background assets of the current panels in the game. Specifically, we need to change the panel where the beasts are displayed and the panel showing the rewards obtained when a battle ends.

- This panel is currently black, and we need to replace it with another asset we already have. This asset will be provided to the contributor once the issue is assigned.

### How this panel is implemented
- This panel is implemented on the prefab called "UI Canvas", this prefab is located in the following path: Assets/Prefabs/UI Canvas.prefab 

- This is how panel hierarchy looks in Unity
<img width="267" alt="Screenshot 2024-10-23 at 1 31 55 PM" src="https://github.com/user-attachments/assets/0b7727c1-08a2-40c1-9400-b90d3791594f">

- This is how the panel looks during gameplay; it is activated by touching the screen with two fingers.

<img width="902" alt="Screenshot 2024-10-23 at 1 29 02 PM" src="https://github.com/user-attachments/assets/3f40e6f1-4320-45c4-86e2-9d4e4e4ca405">

- This is how panel rewards looks when a battle ends
<img width="1125" alt="Screenshot 2024-10-23 at 1 38 35 PM" src="https://github.com/user-attachments/assets/8bca6a25-6560-4e11-8900-d98911eaf1d4">

**Comment by joeperpetua** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bytebeasts).

### My background and how it can be leveraged
Hi guys, Joel from Dojo Coding. 
I have been working with Overdrive in Unity for the past few months :)

**Comment by sebas11042** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bytebeasts).

### My background and how it can be leveraged
I am an advanced computer science student with experience in Java, JavaScript, and Unity. I am currently part of SunsetLabs, where I am responsible for the frontend development of the game Citizen of Arcanis, which we are working on in Unity 3D. This role has provided me with practical experience in asset management, animations, and UI systems in Unity. Given my experience in Unity 3D, I am confident in my ability to tackle issues in Unity 2D and implement solutions efficiently, such as character animations and UI enhancements.

### How I plan on tackling this issue
My idea is to locate the UI Canvas prefab at the specified path (Assets/Prefabs/UI Canvas.prefab) and replace the current background assets of the panels with the new ones that will be provided, ensuring they are properly scaled and aligned. Then, I will conduct visual integration tests to verify that the new assets look good in both the beast display panel and the rewards panel after battles, ensuring they function correctly when activated by a two-finger touch.

**Comment by martinvibes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bytebeasts).

### My background and how it can be leveraged
ello @ i'm a frontend developer and an experienced technical writer i would love to work on this issue 
Pleasee kindly assign :)

**Comment by suhas-sensei** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bytebeasts).

### My background and how it can be leveraged
i have experience in game dev as well as blockchain previously as personal projects and OS, so hoping to make use of them here and mark my first odhack contribution

### How I plan on tackling this issue
I'll implement modular panel styling withh dynamic asset swapping by creating a new BackgroundManager component thatt handles seamless transitions b/w background states. The component will pre-load and cache assets while maintaining aspect ratios, ensure touch interaction consistency, and support future panel variants through a scriptable object-based theme system - all while keeping the existing UI Canvas prefab structure intact.

**Comment by tosoham** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bytebeasts).

### My background and how it can be leveraged
Hi, I am a Python dev, have contributed in OS projects before. I am new to Unity and C# , this will be my first issue in Unity if assigned. Looking forward to solve this issue.

### How I plan on tackling this issue
To approach the task of changing the background assets in Unity, start by locating the "UI Canvas" prefab at Assets/Prefabs/UI Canvas.prefab and identifying the panels responsible for displaying beasts and rewards. Within the panel hierarchy, find the UI elements containing the current black background, which are likely Image components. Replace the black background by assigning the new asset to the Image component's "Source Image" property. Once the new asset is in place, test the panels in-game to ensure they activate correctly—such as the beast panel being triggered by two-finger touch and the rewards panel appearing at the end of a battle. After testing, fine-tune the new background by adjusting size, alignment, or scaling to ensure it fits well within the panel. This process allows the smooth integration of the new assets while maintaining the functionality of the existing panels.

**Comment by blessingbytes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bytebeasts).

### My background and how it can be leveraged
Hello, i'm a frontend and a blockchain developer. Pls i would love to take this.

### How I plan on tackling this issue
Understanding the design and how to interpret it step by step to the desire result using my frontend development skill

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bytebeasts).

### My background and how it can be leveraged
I have a solid background in Unity development, with experience in UI design and asset management. My skills in implementing and modifying UI elements enable me to seamlessly integrate new assets while maintaining the game's visual consistency and functionality.

### How I plan on tackling this issue
To change the background assets of the specified panels, I will locate the "UI Canvas" prefab in the project’s assets. After identifying the panels that require modification, I will replace the current black background with the new asset provided. I will ensure that the asset is correctly positioned and scaled to fit the panels, and I will test the functionality by activating the panels during gameplay to confirm that they display correctly when triggered. This approach ensures a smooth transition to the new visuals while preserving the user experience.

**Comment by FemiOje** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bytebeasts).

### My background and how it can be leveraged
I am a Unity developer(1+ year experience), frontend web developer and smart contract developer. My experience with Unity( especially building 2d projects with emphasis on smooth UX) helps me to more easily understand the codebase and project and therefore eases the contribution process, and my frontend experience helps me to understand how to handle the WebGL builds if needed.

### How I plan on tackling this issue
I have forked the repo and created a "change-assets" branch, and I have examined the project in my Unity editor to further understand the issue. I have also installed the required Unity version for the project (2022.3.28f).

From the Source Image field in the Image component of the beasts panel(UI Canvas/Menu), I will swap out the old assets with the new ones provided.
From the Source Image field in the Image component of the battle rewards section(UI Canvas/ Battle Reward), I will swap out the old panel with the new one provided.
I will then test to make sure that there are no alignment or scaling issues, and that the panels activate whhen the appropriate criteria are fulfilled.

**Comment by FroDev-CR** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bytebeasts).

### My background and how it can be leveraged
As a fronted programmer, member of the CODING DOJO, web designer and lover of video games, I have experience with UI in graphics engines like Unity or Fortnite, and it is an honor for me to contribute to a project like this.
That's why I would like this to be my first issue

### How I plan on tackling this issue
I would start by looking for the links to the Discord or the project telegram to request the documentation, get to that black background and change it, now I have several options for the new color, considering color palettes from the game menus, colors requested by the developers or colors that I believe are correct and pleasing to the eye. This way the developers will have a greater vision of which option is better, thus giving several requests to the issue.

**Comment by 0xBinayak** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bytebeasts).

### My background and how it can be leveraged
I am new to OS but  I have been doing game dev for a year,made 2 personal games and worked on multiple projects in unity with C#.

### How I plan on tackling this issue
I will replace the panel where the beasts are displayed as per as the assets provided and i would keep the functionality exactly the same.
 ETA :1 day

**Comment by aniruddhaaps** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bytebeasts).

### My background and how it can be leveraged
I'm a c# dev. A new-comer here, willing and ready to contribute to solve the issue.

**Comment by jimenezz22** [comment]
gm @joeperpetua assigned to you!
here the panel assets to work:
[ByteBeasts_Panel_Assets.zip](https://github.com/user-attachments/files/17513144/ByteBeasts_Panel_Assets.zip)
Please put this assets in the path Assets/Battle Assets/Art/UI

**Comment by jimenezz22** [comment]
gm @joeperpetua any updates?

**Comment by joeperpetua** [comment]
GM @jimenezz22 
Should have something to push later today :)
